charts/chimera-controller/crds/admissionpolicies.yaml

Handle mutating policies: depends on https://github.com/chimera-kube/chimera-controller/pull/16

Update CR AdmissionPolicy

---

README.md

Update the gh-pages README to reflect the new project's name.

Rename to kubewarden

---

charts/kubewarden-controller/Chart.yaml
charts/kubewarden-controller/README.md
charts/kubewarden-controller/app-readme.md

Fixes https://github.com/kubewarden/helm-charts/issues/8

Add descriptive files for Rancher UI to show for this chart

---

charts/kubewarden-controller/Chart.yaml
charts/kubewarden-controller/crds/clusteradmissionpolicies.yaml
charts/kubewarden-controller/templates/NOTES.txt
charts/kubewarden-controller/templates/configmap.yaml
charts/kubewarden-controller/templates/deployment.yaml
charts/kubewarden-controller/templates/rbac.yaml

Use the latest release of kubewarden-controller: v0.2.0
**NOTE WELL:** do not merge, we still have to tag a new release of kubewarden-controller 0.2.0

Upgrade the kubewarden-controller

---

charts/kubewarden-controller/crds/clusteradmissionpolicies.yaml
charts/kubewarden-controller/crds/policyserver.yaml
charts/kubewarden-controller/templates/deployment.yaml
charts/kubewarden-controller/templates/rbac.yaml

- Add PolicyServer crd
- Update ClusterAdmissionPolicy crd

 Update the custom resources the helm-chart creates

---

charts/kubewarden-controller/templates/configmap.yaml
charts/kubewarden-controller/templates/deployment.yaml
charts/kubewarden-controller/templates/policyserver-default.yaml

Fixes kubewarden/helm-charts#22

Deploy the default PolicyServer by default

---

charts/kubewarden-controller/templates/pre-delete-hook.yaml

Fixes kubewarden/helm-charts#26

Remove PolicyServer resources in a pre-delete helm hook

---

charts/kubewarden-controller/templates/rbac.yaml

fixes kubewarden/helm-charts#27

Add webhooks patch permission to controller role

---

charts/kubewarden-controller/templates/deployment.yaml

Fixes kubewarden/kubewarden-controller#74

LeaderElection - Failed to renew lease time out

---

.github/workflows/helm-chart-release.yml
charts/kubewarden-controller/README.md
charts/kubewarden-controller/values.yaml

Once this is merged, I will commit directly the readme to gh-pages.

Update chart readme

---

charts/kubewarden-controller/Chart.yaml
charts/kubewarden-controller/values.yaml
charts/kubewarden-crds/Chart.yaml
charts/kubewarden-crds/templates/clusteradmissionpolicies.yaml
charts/kubewarden-crds/templates/policyserver.yaml

Include new PolicyServer.spec.{insecureSources, sourceAuthorities}.
Bump policy-server default image tag.

Bump charts: controller 0.3.1, crds 0.1.1

---

charts/kubewarden-controller/Chart.yaml

Please, check if I'm missing something in the helm chart release. If everything is fine, I'm happy to create the tag

Bump controller chart version to 0.3.2, appVersion to v0.4.2

---

charts/kubewarden-controller/templates/deployment.yaml
charts/kubewarden-controller/values.yaml

Tested with `kubectl describe nodes`.
Fixes https://github.com/kubewarden/helm-charts/issues/53.

feat: Expose controller resource limits/requests in Values

---

charts/kubewarden-controller/README.md

We need to trigger a build in our CI to rerelease the Helm chart.

Updates a line format to trigger build in CI.

---

charts/kubewarden-crds/templates/clusteradmissionpolicies.yaml

Depends on: https://github.com/kubewarden/policy-server/pull/194
Depends on: https://github.com/kubewarden/kubewarden-controller/pull/172
Fixes: https://github.com/kubewarden/kubewarden-controller/issues/169

Update ClusterAdmissionPolicy CRD with monitor mode

---

charts/kubewarden-controller/templates/rbac.yaml
charts/kubewarden-controller/templates/webhooks.yaml
charts/kubewarden-crds/templates/admissionpolicy.yaml

Depends on https://github.com/kubewarden/kubewarden-controller/pull/177  
Draft unitl https://github.com/kubewarden/kubewarden-controller/pull/177 is merged
- AdmissionPolicy CRD
- AdmissionPolicy webhooks
Fix kubewarden/kubewarden-controller#10

Add AdmissionPolicy

---

charts/kubewarden-defaults/Chart.yaml

Bumps kubewarden-defaults version to mark the policy server version change.

Bump kubewarden-defaults to v0.1.1.

---

charts/kubewarden-crds/Chart.yaml

Release CRD changes included in https://github.com/kubewarden/helm-charts/commit/eb2a85b74b6c021ce6a301790a5dad2c26940b6c

Bump kubewarden-crds to 0.1.4

---

charts/kubewarden-defaults/Chart.yaml
charts/kubewarden-defaults/chart-values.yaml
charts/kubewarden-defaults/values.yaml

Ensure the latest release of policy-server is being deployed

Update kubewarden-defaults Chart

---

charts/kubewarden-controller/Chart.yaml
charts/kubewarden-crds/Chart.yaml
charts/kubewarden-crds/templates/admissionpolicy.yaml
charts/kubewarden-crds/templates/clusteradmissionpolicies.yaml
charts/kubewarden-crds/templates/policyserver.yaml
charts/kubewarden-defaults/Chart.yaml
charts/kubewarden-defaults/chart-values.yaml
charts/kubewarden-defaults/templates/allow-privileged-escalation-policy.yaml
charts/kubewarden-defaults/templates/host-namespace-policy.yaml
charts/kubewarden-defaults/templates/pod-privileged-policy.yaml
charts/kubewarden-defaults/templates/policyserver-default.yaml
charts/kubewarden-defaults/templates/user-group-policy.yaml
charts/kubewarden-defaults/values.yaml

v1.0.0-rc1 bump

---

charts/kubewarden-controller/templates/webhooks.yaml

Adds the missing v1 apiVersion in the webhook configuration.

Add missing apiVersion.

---

charts/kubewarden-controller/templates/NOTES.txt
charts/kubewarden-controller/templates/webhooks.yaml
charts/kubewarden-defaults/chart-values.yaml
charts/kubewarden-defaults/templates/NOTES.txt
charts/kubewarden-defaults/values.yaml

- Change v1alpha2 for v1 in webhooks
- Add v1 to webhooks path

fix: webhooks don't allow v1alpha2 resources to be created

---

charts/kubewarden-controller/Chart.yaml
charts/kubewarden-crds/Chart.yaml
charts/kubewarden-defaults/Chart.yaml
charts/kubewarden-defaults/chart-values.yaml
charts/kubewarden-defaults/values.yaml

Bump policy-server and controller images to v1.0.0-rc2

Release v1.0.0-rc2

---

charts/kubewarden-controller/Chart.yaml
charts/kubewarden-crds/Chart.yaml
charts/kubewarden-defaults/Chart.yaml
charts/kubewarden-defaults/chart-values.yaml
charts/kubewarden-defaults/values.yaml

Tag 1.0.0-rc3

---

charts/kubewarden-controller/Chart.yaml
charts/kubewarden-crds/Chart.yaml
charts/kubewarden-defaults/Chart.yaml
charts/kubewarden-defaults/chart-values.yaml
charts/kubewarden-defaults/values.yaml

This is required to get the latest version of Policy Server which can now handle `DELETE` operations.

Tag 1.0.0-rc4 release

---

charts/kubewarden-controller/Chart.yaml
charts/kubewarden-crds/Chart.yaml
charts/kubewarden-defaults/Chart.yaml
charts/kubewarden-defaults/chart-values.yaml
charts/kubewarden-defaults/values.yaml

Tag 1.0.0 release

---

charts/kubewarden-defaults/Chart.yaml
charts/kubewarden-defaults/chart-values.yaml
charts/kubewarden-defaults/values.yaml

bump policy-server to v1.0.1

---

.github/workflows/helm-chart-release.yml
charts/kubewarden-controller/Chart.yaml
charts/kubewarden-crds/Chart.yaml
charts/kubewarden-defaults/Chart.yaml
charts/kubewarden-defaults/chart-values.yaml
charts/kubewarden-defaults/values.yaml

- Revert config of helm action, it doesn't work.
- Bump for v1.1.0.

Road to 1.1.0

---

charts/kubewarden-defaults/Chart.yaml
charts/kubewarden-defaults/chart-values.yaml
charts/kubewarden-defaults/values.yaml

Updates the default pod privileged policy version used to v0.2.0.

feat: updates pod priviliged policy version.

---

charts/kubewarden-defaults/Chart.yaml
charts/kubewarden-defaults/README.md

Updates the README.md file adding documentation for the configuration fields of the recommended policies.

Document recommendedPolicies configuration.

---

charts/kubewarden-defaults/Chart.yaml
charts/kubewarden-defaults/chart-values.yaml
charts/kubewarden-defaults/values.yaml

Updates the kubewarden-defaults chart to use policy server version v1.1.2.

Updates policy-server version to v1.1.2.

---

charts/kubewarden-controller/README.md

Fix https://charts.kubewarden.io/#configuration

Fix typo: add missing backtick

---

charts/kubewarden-defaults/README.md

Links point to non-existent pages

Fix broken links to policies

---

charts/kubewarden-controller/Chart.yaml

Correctly set appVersion to 1.1.0, and release kubewarden-controller 1.1.1.

Release kubewarden-controller 1.1.1

---

charts/kubewarden-controller/Chart.yaml
charts/kubewarden-controller/chart-values.yaml
charts/kubewarden-controller/templates/deployment.yaml
charts/kubewarden-controller/templates/pre-delete-hook.yaml
charts/kubewarden-controller/values.yaml
charts/kubewarden-crds/Chart.yaml
charts/kubewarden-defaults/Chart.yaml

partial implementation of https://github.com/kubewarden/rfc/pull/11.
The resulting charts can be consumed in Rancher UI, but can't yet be served through Rancher mirrors.
Resulting charts are backwards compatible and no major nor minor version bump is needed.
Missing:
- kubewarden-defaults hard-depend on controller. `requires-gvr` annot doesn't seem to work. Not important, as I suppose prior to inclusion in Rancher UI, we would mark all charts but `kubewarden-controller` as `hidden`, and use Kubewarden UI to install `kubewarden-defaults`.
- Changes to `kubewarden-defaults` values to mirror wasm modules, from `module` to `module.registry`, `module.tag`. These are breaking semver changes, and if implemented in kubewarden charts pustream, would necessitate a major version bump.
- Mirroring …

feat: Add Rancher integration as upstream charts, release 1.2.0

---

charts/kubewarden-controller/Chart.yaml
charts/kubewarden-controller/chart-values.yaml
charts/kubewarden-controller/values.yaml
charts/kubewarden-crds/Chart.yaml
charts/kubewarden-crds/templates/admissionpolicy.yaml
charts/kubewarden-crds/templates/clusteradmissionpolicies.yaml
charts/kubewarden-crds/templates/policyserver.yaml
charts/kubewarden-defaults/Chart.yaml

Fix https://github.com/kubewarden/kubewarden-controller/issues/265
Update CRDs shipped in `kubewarden-crds`.
Update controller image used in `kubewarden-controller`,
Update `auto-installs` dependency annot in `kubewarden-controller`, `kubewarden-defaults`.
Bump all charts pach versions to ship their changes.

feat: Bump patch version of charts to release new controller, CRDs versions

---

charts/kubewarden-controller/Chart.yaml
charts/kubewarden-crds/Chart.yaml
charts/kubewarden-defaults/Chart.yaml

Update maintainers info with the new Kubewarden Maintainers group.

docs: Update maintainers info with new Maintainers group

---

charts/kubewarden-controller/Chart.yaml
charts/kubewarden-controller/chart-values.yaml
charts/kubewarden-controller/values.yaml
charts/kubewarden-defaults/Chart.yaml
charts/kubewarden-defaults/chart-values.yaml
charts/kubewarden-defaults/values.yaml

New RC of the Kubewarden stack

Release Kubewarden 1.3.0-rc2

---

charts/kubewarden-controller/Chart.yaml
charts/kubewarden-controller/chart-values.yaml
charts/kubewarden-controller/values.yaml
charts/kubewarden-defaults/Chart.yaml
charts/kubewarden-defaults/chart-values.yaml
charts/kubewarden-defaults/values.yaml

1.3.0-rc3 release

---

charts/kubewarden-controller/Chart.yaml
charts/kubewarden-controller/chart-values.yaml
charts/kubewarden-controller/values.yaml
charts/kubewarden-defaults/Chart.yaml
charts/kubewarden-defaults/chart-values.yaml
charts/kubewarden-defaults/values.yaml

Release Kubewarden stack 1.3.0

---

.github/workflows/helm-chart-release.yml
.gitignore
Makefile
scripts/extract_images.sh

Upload to the chart releases an asset containing all the container images used in the chart.
Fix https://github.com/kubewarden/helm-charts/issues/150

Upload image files.

---

.github/workflows/ci.yaml
.github/workflows/helm-chart-release.yml
.gitignore
Makefile
charts/kubewarden-defaults/Chart.yaml
charts/kubewarden-defaults/chart-values.yaml
charts/kubewarden-defaults/templates/allow-privileged-escalation-policy.yaml
charts/kubewarden-defaults/templates/capabilities-policy.yaml
charts/kubewarden-defaults/templates/host-namespace-policy.yaml
charts/kubewarden-defaults/templates/host-path-policy.yaml
charts/kubewarden-defaults/templates/pod-privileged-policy.yaml
charts/kubewarden-defaults/templates/user-group-policy.yaml
charts/kubewarden-defaults/values.yaml
scripts/extract_images.sh
scripts/extract_policies.sh

Adds script and CI step to generate a file to store the Kubewarden policies used in the kubewarden-defaults Helm chart. This file is added in the chart tarball and uploaded in the Github release.

Policies list

---

charts/kubewarden-controller/Chart.yaml
charts/kubewarden-defaults/Chart.yaml
charts/kubewarden-defaults/chart-values.yaml
charts/kubewarden-defaults/values.yaml

Depends on [policy-server 1.4.0-rc1 finishing building.](https://github.com/kubewarden/policy-server/actions/runs/3594420940)
Support Sigstore verification via x509 certs, x509 certs verification
To be performed with e2e tests.

Bump to 1.4.0-rc1

---

.github/workflows/helm-chart-release.yml
artifacthub-repo.yml
charts/kubewarden-controller/Chart.yaml
charts/kubewarden-controller/chart-values.yaml
charts/kubewarden-controller/values.yaml
charts/kubewarden-crds/Chart.yaml
charts/kubewarden-defaults/Chart.yaml

This mainly just includes the controller image 1.4.0-rc1.
To be tested with e2e tests.

Bump to 1.4.0-rc2

---

charts/kubewarden-controller/Chart.yaml
charts/kubewarden-controller/chart-values.yaml
charts/kubewarden-controller/values.yaml
charts/kubewarden-defaults/Chart.yaml
charts/kubewarden-defaults/chart-values.yaml
charts/kubewarden-defaults/values.yaml

Bump controller, policy-server image to 1.4.0.
Bump charts for 1.4.0.
To be done with e2e tests, rc2 was fine.

 Bump to 1.4.0 

---

charts/kubewarden-defaults/Chart.yaml
charts/kubewarden-defaults/chart-values.yaml
charts/kubewarden-defaults/templates/allow-privileged-escalation-policy.yaml
charts/kubewarden-defaults/templates/pod-privileged-policy.yaml
charts/kubewarden-defaults/templates/user-group-policy.yaml
charts/kubewarden-defaults/values.yaml

Updates the recommended policies to the latest version and updates the policies definition to target high level resources when possible.

chore: update recommended policies to latest versions.

---

.github/workflows/e2e-tests.yml

Adds a new Github workflow to run the end to end tests on every PR into main branch. As well as changes in any branch and new tags.
Fix #161

End to end tests.

---

charts/kubewarden-defaults/chart-values.yaml
charts/kubewarden-defaults/templates/_helpers.tpl
charts/kubewarden-defaults/templates/allow-privileged-escalation-policy.yaml
charts/kubewarden-defaults/templates/capabilities-policy.yaml
charts/kubewarden-defaults/templates/host-namespace-policy.yaml
charts/kubewarden-defaults/templates/host-path-policy.yaml
charts/kubewarden-defaults/templates/pod-privileged-policy.yaml
charts/kubewarden-defaults/templates/user-group-policy.yaml
charts/kubewarden-defaults/values.yaml

Adds a new global value to allow user configure a different registry used in the policies module field.
Fix #242

feat: default policy module repository value.

---

.github/workflows/helm-chart-release.yml
charts/kubewarden-controller/chart-values.yaml
charts/kubewarden-controller/values.yaml

Relates to https://github.com/kubewarden/kubewarden-controller/issues/411
On CI, next RC.

ci: Update cosign-installer gha to v3

---

charts/kubewarden-controller/chart-values.yaml
charts/kubewarden-controller/values.yaml

Updates the kubewarden-controller chart updating the kubectl image tag used in the pre delete job.

fix: update kubectl image tag.

---

charts/kubewarden-defaults/templates/NOTES.txt

Relates to https://github.com/kubewarden/helm-charts/pull/299.
feat: Add conditional for monitor policies in NOTES.txt
CI, as it is the default behaviour.

feat: Add conditional for monitor policies in NOTES.txt

---

.github/workflows/update-charts.yml

ci: Update controller chart if audit-scanner changes CRDs

---

charts/README.md

This PR updates README present in the `charts` directory. It provides the users information about the installation sequence of the charts.
To test this pull request, you can run the following commands: N/A because this is a documentation change.
N/A
N/A

docs: Update charts' README

---

renovate.json

Fix https://github.com/kubewarden/helm-charts/issues/319

ci: Fix renovate.json format

---

renovate.json

Second try of https://github.com/kubewarden/helm-charts/pull/314.
Not tested, will see after running renovate.

deps: Skip policy-reporter-ui 1.15.1

---

renovate.json

Another try, after https://github.com/kubewarden/helm-charts/pull/323.
The package name is `ghcr.io/kyverno/policy-reporter-ui`, let's go overly cautious and accept any prefix.
Tested locally:
```
$ LOG_LEVEL=debug RENOVATE_CONFIG_FILE=./renovate.json npx renovate --platform=local --require-config=ignored
...
{
"depName": "ghcr.io/kyverno/policy-reporter-ui",
"currentValue": "1.9.0",
"datasource": "docker",
"replaceString": "1.9.0",
"versioning": "docker",
"autoReplaceStringTemplate": "{{newValue}}{{#if newDigest}}@{{newDigest}}{{/if}}",
"updates": [],
"packageName": "ghcr.io/kyverno/policy-reporter-ui",
"warnings": [],
"registryUrl": "https://ghcr.io",
"currentVersion": "1.9.0",
"fixedVersion": "1.9.0"
}
```

deps: Actually skop policy-reporter-ui v1.15.1

---

charts/kubewarden-controller/Chart.yaml

Fix https://github.com/kubewarden/helm-charts/issues/327
Untested, as its pretty simple.

chore: Declare support for rancher-version <= 2.8.100-0

---

charts/kubewarden-controller/chart-values.yaml
charts/kubewarden-controller/values.yaml
charts/kubewarden-defaults/chart-values.yaml
charts/kubewarden-defaults/values.yaml

deps: Consume RC container images

---

CONTRIBUTING.md

docs: Add CONTRIBUTING.md with release steps

---

CONTRIBUTING.md

Update CONTRIBUTING.md with CI workaround

---

charts/kubewarden-controller/Chart.yaml
charts/kubewarden-controller/chart-values.yaml
charts/kubewarden-controller/values.yaml

Reverts kubewarden/helm-charts#343

Revert "Helm chart patch release"

---

charts/kubewarden-controller/chart-values.yaml
charts/kubewarden-controller/values.yaml

Consume correct audit-scanner v1.8.1.
CI

Actually release kubewarden-controller 2.0.2

---

charts/kubewarden-controller/Chart.yaml
charts/kubewarden-controller/chart-values.yaml
charts/kubewarden-controller/values.yaml
charts/kubewarden-crds/Chart.yaml
charts/kubewarden-defaults/Chart.yaml
charts/kubewarden-defaults/chart-values.yaml
charts/kubewarden-defaults/values.yaml

Release v1.9.0-rc3

---

charts/kubewarden-controller/Chart.yaml
charts/kubewarden-controller/chart-values.yaml
charts/kubewarden-controller/values.yaml
charts/kubewarden-crds/Chart.yaml
charts/kubewarden-defaults/Chart.yaml
charts/kubewarden-defaults/chart-values.yaml
charts/kubewarden-defaults/values.yaml

Release 1.9.0.
This is the diff against latest GA, 1.8.1: https://github.com/kubewarden/helm-charts/compare/kubewarden-controller-2.0.2...viccuad:helm-charts:v1.9.0
CI

Release Kubewarden v1.9.0

---

CONTRIBUTING.md

Add docs generation and algolia to releasing workflow

---

charts/kubewarden-controller/chart-values.yaml
charts/kubewarden-controller/values.yaml
charts/kubewarden-defaults/chart-values.yaml
charts/kubewarden-defaults/values.yaml

deps: Bump policies, kubectl image

---

charts/kubewarden-defaults/chart-values.yaml
charts/kubewarden-defaults/values.yaml

deps: Bump pod-privileged policy to v0.3.1

---

charts/kubewarden-controller/Chart.yaml
charts/kubewarden-controller/chart-values.yaml
charts/kubewarden-controller/values.yaml
charts/kubewarden-crds/Chart.yaml
charts/kubewarden-crds/templates/clusteradmissionpolicies.yaml
charts/kubewarden-crds/templates/policyservers.yaml
charts/kubewarden-defaults/Chart.yaml
charts/kubewarden-defaults/chart-values.yaml
charts/kubewarden-defaults/values.yaml

CI.
Policy-reporter was smoke tested manually.
Here is the diff from the last release to this PR:
https://github.com/kubewarden/helm-charts/compare/kubewarden-controller-2.0.5...viccuad:helm-charts:road-to-1.10.0-rc1
No significant chart changes, just some bug fixes, hence the chart versions only get a patch bump.

Release Kubewarden 1.10.0-rc1

---

charts/kubewarden-controller/Chart.yaml
charts/kubewarden-controller/chart-values.yaml
charts/kubewarden-controller/values.yaml
charts/kubewarden-crds/Chart.yaml
charts/kubewarden-defaults/Chart.yaml
charts/kubewarden-defaults/chart-values.yaml
charts/kubewarden-defaults/values.yaml

Bump to 1.10.0-rc2

---

charts/kubewarden-controller/Chart.yaml
charts/kubewarden-controller/chart-values.yaml
charts/kubewarden-controller/values.yaml
charts/kubewarden-crds/Chart.yaml
charts/kubewarden-defaults/Chart.yaml
charts/kubewarden-defaults/chart-values.yaml
charts/kubewarden-defaults/values.yaml

For a comparison from Kubewarden 1.9 to Kubewarden 1.10:
https://github.com/kubewarden/helm-charts/compare/kubewarden-defaults-1.9.2...road-to-1.10.0
CI

Release Kubewarden 1.10.0

---

.github/workflows/update-charts.yml

Allow to trigger the Updatecli job via the GitHub UI
Fix #307 
It's not possible to test without merging :)

chore: allow to trigger update-charts.yml via ui

---

charts/kubewarden-defaults/values.yaml

updatecli mangled the yaml comments.

chore: Comments on kubewarden-defaults values.yaml

---

charts/kubewarden-crds/templates/policyservers.yaml
charts/kubewarden-defaults/templates/policyserver-default.yaml
charts/kubewarden-defaults/values.yaml

Fix https://github.com/kubewarden/kubewarden-controller/issues/701
feat: Add policyserver.affinity value to kubewarden-defaults 
Tested manually. Needs controller:latest.

feat: Add policyserver.affinity value to kubewarden-defaults 

---

updatecli/updatecli.d/update-deps.yaml

ci: Add reminders to automated PR description

---

charts/kubewarden-controller/Chart.yaml

Fix https://github.com/kubewarden/helm-charts/issues/445
This declares support for Rancher v2.9-x versions
CI, e2e tests on main.

chore: Bump rancher-version annot to <= 2.9.100-0

---

charts/kubewarden-defaults/Chart.yaml
charts/kubewarden-defaults/templates/policyserver-default.yaml

This reverts commit e514fa7c65c45f3d631544e15c6a55208169a765. This is necessary because the controller using the same finalizer is not released yet.

Revert the default policy server finalizer in use

---

charts/kubewarden-defaults/templates/policyserver-default.yaml

As the v1.14.0-rc1 controller is near to be released. It's necessary to add the new domain qualified finalizer in default policy server.

Update policy server default finalizer.

---

charts/kubewarden-controller/Chart.yaml
charts/kubewarden-controller/templates/rbac.yaml

Updates the role that give permissions to the controller manipulate the PodDisruptionBudget resource. The role is missing the "patch" verb.

fix: add patch verb to the PDB resource.

---

charts/kubewarden-controller/templates/opentelemetry-collector.yaml

Fix https://github.com/kubewarden/helm-charts/issues/474
Tested by performing a manual helm upgrade over kubewarden with telemetry deployed using kubewarden-end-to-end-tests.

deps: Bump OpenTelemetryCollector to v1beta1

---

artifacthub-repo.yml
charts/kubewarden-controller/Chart.yaml
charts/kubewarden-crds/Chart.yaml
charts/kubewarden-defaults/Chart.yaml
updatecli/values.yaml

chore: Update maintainers e-mail address

---

charts/kubewarden-crds/values.schema.json

This gives us the schema badge for this chart in artifacthub.io.
Tested locally.

feat: Add values.schema.json for kubewarden-crds chart

---

charts/kubewarden-crds/templates/NOTES.txt
charts/kubewarden-crds/templates/admissionpolicygroups.yaml
charts/kubewarden-crds/templates/clusteradmissionpolicygroups.yaml

Updates policy groups CRDs, including fixes from: https://github.com/kubewarden/kubewarden-controller/pull/878

chore: update policy groups CRDs

---

.github/workflows/e2e-tests.yml

Schedule PR tests
Local run: https://github.com/kravciak/helm-charts/actions/runs/10831677457

Helm chart testing

---

charts/kubewarden-controller/templates/webhooks.yaml
charts/kubewarden-controller/tests/webhooks_test.yaml

Fixes: #536 
The bug happens only in Kubernetes <= 1.24

fix: unknown object type "nil" error in Kubernetes <= v1.24

---

charts/kubewarden-defaults/templates/NOTES.txt

fix(kubewarden-defaults): module output in NOTES.txt

---

Makefile
charts/kubewarden-controller/Chart.yaml

Moreover, add make target to run unit tests locally

fix: address broken yaml file

---

charts/kubewarden-defaults/templates/NOTES.txt

```
- no-privilege-escalation
module: ghcr.io://kubewarden/policies/allow-privilege-escalation-psp:v0.2.6
- no-privilege-escalation
module: registry://ghcr.io/kubewarden/policies/allow-privilege-escalation-psp:v0.2.6
```

Fix chart installation notes

---

updatecli/updatecli.d/major-kubewarden-update-with-crd-update.yaml
updatecli/updatecli.d/major-kubewarden-update.yaml
updatecli/updatecli.d/patch-kubewarden-controller-with-crds-update.yaml
updatecli/updatecli.d/patch-kubewarden-controller.yaml
updatecli/updatecli.d/patch-kubewarden-defaults.yaml
updatecli/updatecli.d/prerelease-kubewarden-update-with-crd-update.yaml
updatecli/updatecli.d/prerelease-kubewarden-update.yaml
updatecli/updatecli.d/update-deps.yaml

Same approach as in the cel-policy repo. Assumed to work.

ci: add Signed-off-by to updatecli commits

---

updatecli/updatecli.d/major-kubewarden-update-with-crd-update.yaml
updatecli/updatecli.d/major-kubewarden-update.yaml
updatecli/updatecli.d/patch-kubewarden-controller-with-crds-update.yaml
updatecli/updatecli.d/patch-kubewarden-controller.yaml
updatecli/updatecli.d/patch-kubewarden-defaults.yaml
updatecli/updatecli.d/prerelease-kubewarden-update-with-crd-update.yaml
updatecli/updatecli.d/prerelease-kubewarden-update.yaml
updatecli/updatecli.d/update-deps.yaml

Proper changes for https://github.com/kubewarden/helm-charts/pull/546.
We will see on follow-up update-cli PRs.

ci: Fix Signed-off-by footers to the ones expected

---

charts/kubewarden-controller/Chart.yaml

chore: Declare compatibility with rancher 2.10

---

charts/kubewarden-controller/templates/opentelemetry-collector.yaml

Updates the OpenTelemetry CRDs to v1beta1 version.
Fix #579

fix: update OpenTelemetry CRDs

---

charts/kubewarden-controller/questions.yaml

Renames the "Telemetry" group to "OpenTelemetry" in questions.yaml.
Related to #597

fix: rename telemetry grup.

---

charts/kubewarden-controller/Chart.yaml

Updates the kubewarden-controller v4.0.0-rc2 to release the fixes in the questions.yaml file.

chore: release kubewarden-controller v4.0.0-rc2

---

charts/kubewarden-controller/Chart.yaml

Fix https://github.com/kubewarden/helm-charts/issues/612

feat: Declare support for Rancher 2.11.X

---

charts/kubewarden-controller/templates/_helpers.tpl
charts/kubewarden-controller/templates/audit-scanner.yaml
charts/kubewarden-controller/templates/webhooks.yaml
charts/kubewarden-controller/tests/webhooks_existing_certifcates_test.yaml
charts/kubewarden-controller/tests/webhooks_test.yaml

Fixes  https://github.com/kubewarden/audit-scanner/issues/462
~NOTE: e2e tests are not passing since it is not using the latest images.~
e2e tests are now passing

feat: add audit scanner mtls support

---

.github/workflows/e2e-tests.yml

Changes described in https://github.com/kubewarden/kubewarden-controller/issues/1096
Depends on https://github.com/kubewarden/kubewarden-end-to-end-tests/pull/168

Install bats npm from official package

---

.github/workflows/e2e-airgap.yml

We need to know which versions we are about to install by browsing imagelist files in helm charts.
https://github.com/juadk/helm-charts/actions/runs/15485676625 ✅

Extract component versions for airgap deployment

---

.github/workflows/helm-chart-release.yml

Updates the Helm chart release job adding a debugging message to double check the Helm version in use.

chore: debugging step in release job before chart releaser installation.

---

.github/workflows/helm-chart-release.yml

Remove gh-pages update for the following.
- Not much user to use
- Readme is outdate

chore: remove ghpage update.
