kubewarden/helm-charts

charts/kubewarden-controller/Chart.yaml
charts/kubewarden-controller/templates/deployment.yaml
charts/kubewarden-controller/templates/policy-server-rbac.yaml
charts/kubewarden-controller/values.yaml

Implements https://github.com/kubewarden/helm-charts/issues/4
The `policy-server` requires to list well known resources, so
context-aware policies can take decisions based on this information.
While this permissions, and what resources can be listed and watched
will be customizable in the future, right now is a fixed set of
resources:
- Namespaces
- Services
- Ingresses
This list is customizable by overriding the helm chart `values.yaml`.

Add context awareness RBAC permissions

---

charts/kubewarden-controller/Chart.yaml
charts/kubewarden-controller/values.yaml

Deploy the latest stable release of the policy-server container image.
This release allows to use Rego based policies too, like the ones created with Open Policy Agent and Gatekeeper.
Update policy-server image to v0.2.0.
Note well: this is still based on the old architecture.

Update the helm chart: enable rego support

---

charts/kubewarden-controller/README.md
charts/kubewarden-controller/crds/clusteradmissionpolicies.yaml
charts/kubewarden-controller/crds/policyserver.yaml
charts/kubewarden-controller/templates/cert-tls.yaml
charts/kubewarden-controller/templates/deployment.yaml
charts/kubewarden-controller/templates/policyserver-default.yaml
charts/kubewarden-controller/templates/service.yaml
charts/kubewarden-controller/templates/webhooks.yaml
charts/kubewarden-controller/values.yaml

- Add cert-manager as dependency, and template resources with its annotations, with `tls.useCertManager` (default `true`).
- Create cert-manager self-signed Issuer and Certificate, with `tls.useSelfSignedCert` (default `true`).
- Bump CRDs for new ClusterAdmissionPolicy.spec.status, add wehbook-server configuration for resources.
- Create default PolicyServer with a helm post-install hook (and use `helm install --wait`), as if not it will fail with the new webhooks.
- Update README.md
Part of https://github.com/kubewarden/helm-charts/issues/32.

Add webhook server, cert-manager support

---

charts/kubewarden-controller/templates/policyserver-default.yaml
charts/kubewarden-controller/values.yaml

Allow the user to specify some configuration values for the default PolicyServer object created by the chart.

Allow tuning of the default PolicyServer

---

.github/workflows/helm-chart-release.yml

Ensure the `.nojekyll` file is not created. This prevents the gh-pages from rendering the contents of the `README.md`, which causes a 404 when opening https://charts.kubewarden.io

Attempt to fix gh pages release

---

charts/kubewarden-controller/templates/deployment.yaml
charts/kubewarden-controller/templates/opentelemetry-collector.yaml
charts/kubewarden-controller/templates/policyserver-default.yaml
charts/kubewarden-controller/values.yaml

Related: https://github.com/kubewarden/policy-server/issues/106
Add an initial OpenTelemetry integration to the helm charts.
The current configuration is not very flexible, in that it allows to change (or disable -- by using `null`) the metrics port. And the jaeger service to push traces to.
In other setups, where the agent (sidecar) collector, can send to other gateway collector running as a service in the cluster, this is not supported in this scheme.
There is always this balance between how easy we make to do a helm install without changing `values.yaml` that much, and how much freedom we let the user to configure.

OpenTelemetry: add integration

---

charts/kubewarden-controller/templates/deployment.yaml
charts/kubewarden-controller/templates/opentelemetry-collector.yaml
charts/kubewarden-controller/templates/policyserver-default.yaml
charts/kubewarden-controller/templates/service.yaml
charts/kubewarden-controller/values.yaml

Updates the Kubearden controller Helm chart to allow the user to enable metrics. Thus, OpenTelemetry can collect and expose these metrics to be collected by Prometheus.
This PR does not allow a fine-grain control of the metrics. This means that, if the user enables the telemetry. It will enable the metrics in the controller and policy servers. If we wanna allow the user to enable just for one component of the stack, I need to update the PR.

Enable Kubewarden controller metrics.

---

charts/kubewarden-controller/Chart.yaml
charts/kubewarden-controller/values.yaml

Updates the policy server version to v0.2.5. This is the first version with the policy evaluation latency metric.

Bumps policy server version to v0.2.5.

---

.github/workflows/helm-chart-release.yml

Updates the helm-chart-release.yml adding a environment variable to configure the helm chart releaser to skip the upload of a release which already exist.

Skip releases if they already exist.

---

charts/kubewarden-controller/Chart.yaml
charts/kubewarden-crds/templates/admissionpolicy.yaml
charts/kubewarden-crds/templates/clusteradmissionpolicies.yaml
charts/kubewarden-crds/templates/policyserver.yaml
charts/kubewarden-defaults/templates/policyserver-default.yaml
charts/kubewarden-defaults/values.yaml

Fix https://github.com/kubewarden/helm-charts/issues/68
Depends on https://github.com/kubewarden/kubewarden-controller/pull/193
Depends on https://github.com/kubewarden/kubewarden-controller/pull/194
Consumes new versions of controller, policy-server, and crds that allow for Sigstore verification.
On `kubewarden-defaults` chart: Expose `policyServer.VerificationConfig` for default PolicyServer
```shell
kubectl apply -f https://github.com/jetstack/cert-manager/releases/latest/download/cert-manager.yaml
kubectl wait --for=condition=Available deployment --timeout=2m -n cert-manager --all
helm install --wait -n kubewarden --create-namespace kubewarden-crds ./kubewarden-crds
helm install --wait -n kubewarden kubewarden-controller …
```

Expose `policyServer.VerificationConfig` for default PolicyServer

---

charts/kubewarden-controller/Chart.yaml
charts/kubewarden-crds/templates/admissionpolicy.yaml
charts/kubewarden-crds/templates/clusteradmissionpolicies.yaml
charts/kubewarden-crds/templates/policyserver.yaml
charts/kubewarden-defaults/templates/policyserver-default.yaml
charts/kubewarden-defaults/values.yaml

Reverts kubewarden/helm-charts#72
Reverting, as I didn't realize we have this open and to be merged already: https://github.com/kubewarden/helm-charts/pull/73
Merging this would release the Sigstore story charts.

Revert "Expose `policyServer.VerificationConfig` for default PolicyServer"

---

charts/kubewarden-controller/Chart.yaml

Bumps kubewarden-controller version to trigger a new release. This is necessary due an issue in the release process.

Bump kubewarden-controller version.

---

charts/kubewarden-controller/Chart.yaml
charts/kubewarden-crds/Chart.yaml

Bumps kubewarden-controller version to v0.4.2 and kubewarden-crds version to v0.1.3 to mark the release of the secure supply chain changes.

Bumps kubewarden-controller and kubewarden-crds versions.

---

charts/kubewarden-controller/templates/rbac.yaml

Updates the roles used by the Kubewarden controller to allow the process access pod resources information. This is necessary due the latest changes in the controller where it watches for pod updates.
Related to https://github.com/kubewarden/kubewarden-controller/pull/199

Controller pod permissions.

---

charts/kubewarden-controller/Chart.yaml
charts/kubewarden-controller/templates/deployment.yaml
charts/kubewarden-controller/values.yaml
charts/kubewarden-defaults/templates/allow-privileged-escalation-policy.yaml
charts/kubewarden-defaults/templates/host-namespace-policy.yaml
charts/kubewarden-defaults/templates/pod-privileged-policy.yaml
charts/kubewarden-defaults/templates/policyserver-default.yaml
charts/kubewarden-defaults/templates/user-group-policy.yaml
charts/kubewarden-defaults/values.yaml

Fixes: https://github.com/kubewarden/helm-charts/issues/76
This adds a global `values.yaml` file that can be consumed by the subcharts on certain attributes that might be shared across them.
For installation, the current documentation can be followed, running:
```
$ helm install --wait -n kubewarden --create-namespace kubewarden-crds charts/kubewarden-crds -f values.yaml
$ helm install --wait -n kubewarden kubewarden-controller charts/kubewarden-controller -f values.yaml
$ helm install --wait -n kubewarden kubewarden-defaults charts/kubewarden-defaults -f values.yaml
```
You can read more about global values at https://helm.sh/docs/chart_template_guide/subcharts_and_globals/#global-chart-values

Add default policy server settings

---

charts/kubewarden-defaults/Chart.yaml
charts/kubewarden-defaults/README.md
charts/kubewarden-defaults/chart-values.yaml
charts/kubewarden-defaults/templates/policyserver-default.yaml
charts/kubewarden-defaults/values.yaml

Adds the values `imagePullSecret`, `insecureSources` and `sourceAuthorities`
allowing the users to configure the policy server configuration with the
same name.
Fix #84

Add missing policyServer configuration values.

---

charts/kubewarden-defaults/chart-values.yaml
charts/kubewarden-defaults/values.yaml

Our README.md shows the telemetry disable by default. However, it is enabled by default in the chart-values.yaml file. Therefore, this commit change it disabling it again.

Telemetry should be disabled by default.

---

charts/kubewarden-defaults/Chart.yaml
charts/kubewarden-defaults/templates/allow-privileged-escalation-policy.yaml

The recommended policy to control privileged escalation requires the permission to mutate requests. However, the policy definition does not allow the policy to mutate requests. This commit fixes that changing the mutating flag to "true". Therefore, the policy can run properly.
Issue found during testing for the issue https://github.com/kubewarden/policy-server/issues/260

The allow privileged escalation policy should be able to mutate.

---

charts/kubewarden-controller/chart-values.yaml
charts/kubewarden-controller/templates/pre-delete-hook.yaml
charts/kubewarden-controller/values.yaml

Use `kubewarden/kubectl` image, which is signed, instead of `rancher-kubectl`.
Parametrize the image with values.yaml.
Tested the pre-delete hook locally, with an image built by the same code as https://github.com/kubewarden/rancher-kubectl-builder/pull/2 (ghcr.io/viccuad/kubectl)
Depends on https://github.com/kubewarden/rancher-kubectl-builder/pull/2, and that workflow being run and new images being generated.

feat: Use `kubewarden/kubectl` image which is signed

---

.github/workflows/helm-chart-release.yml

Adds another job in the Github workflow to package, sign and publish all the Helm chart in the Github OCI registry.
Fix #92 
After releasing the chart with the added jobs, you can download the chart with the following commands:
```shell
helm install myrelease oci://ghrc.io/kubewarden/charts/kubewarden-controller --version 0.4.6
```
See more info about helm commands at https://helm.sh/docs/topics/registries/

Release Helm chart to OCI registry.

---

.github/workflows/helm-chart-release.yml

With the new install-helm v3 action, we can just ask for the latest Helm 3.* version.

feat: Install latest Helm 3.* in GHA

---

charts/kubewarden-defaults/Chart.yaml
charts/kubewarden-defaults/chart-values.yaml
charts/kubewarden-defaults/values.yaml

Use the latest patch release of Policy Server. This is required to have a workaround for an issue with the Sigstore TUF repository.

Consume Policy Server v1.1.1

---

charts/kubewarden-defaults/Chart.yaml
charts/kubewarden-defaults/chart-values.yaml
charts/kubewarden-defaults/templates/capabilities-policy.yaml
charts/kubewarden-defaults/templates/host-path-policy.yaml
charts/kubewarden-defaults/values.yaml

Adds two more recommended policies. The first policy will control which host paths can be used with the `hostPath` volume type. The second one will ensure that no container will have more Linux capabilities than necessary.
Fix #90 
Fix #91

feat: add policies to control host paths and container capabilities.

---

charts/kubewarden-controller/Chart.yaml
charts/kubewarden-controller/README.md
charts/kubewarden-controller/chart-values.yaml
charts/kubewarden-controller/values.yaml
charts/kubewarden-defaults/Chart.yaml
charts/kubewarden-defaults/README.md

Merge "Configuration" sections of charts into their values.yaml, using values.yaml and its comments as canonical source for documentation that is DRY.

merge docs into values.yaml, bump kubewarden-controller & kubewarden-charts

---

charts/kubewarden-defaults/Chart.yaml
charts/kubewarden-defaults/templates/capabilities-policy.yaml

If no:
`.Values.recommendedPolicies.capabilitiesPolicy.allowed_capabilities`
`.Values.recommendedPolicies.capabilitiesPolicy.required_drop_capabilities`
are passed, then we get incorrect settings rendered such as:
```
settings:
allowed_capabilities: null
default_add_capabilities: null
required_drop_capabilities:
- ALL
```
Skip rendering `settings.recommendedPolicies.capabilitiesPolicy` if their array is empty.
`helm template charts/kubewarden-defaults --set recommendedPolicies.enabled=True`
which renders just `required_drop_capabilities: [ - ALL ]`,
and `helm template charts/kubewarden-defaults --values
capabilities-values.yml` with some settings, which renders those
settings correctly.

Fix capabilities values

---

charts/kubewarden-controller/Chart.yaml
charts/kubewarden-defaults/Chart.yaml

Hide `kubewarden-defaults`, show `kubewarden-controller` as `Kubewarden`.
To test, install Rancher and then add the Kubewarden charts from the UI:
```shell
minikube start --kubernetes-version=v1.23.9
minikube addons enable ingress
kubectl create namespace cattle-system
kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.7.2/cert-manager.crds.yaml
helm install --wait \
cert-manager jetstack/cert-manager \
--namespace cert-manager \
--create-namespace \
--version v1.7.1
helm install rancher rancher-latest/rancher \
--namespace cattle-system \
--set hostname=rancher.local \
--set replicas=1 \
--set bootstrapPassword=password
```
Don't delete branch, please. This is a feature branch containing all rancher-needed modifications.

feat(Rancher): Hide `kubewarden-defaults`, show `kubewarden-controller` as `Kubewarden`

---

charts/kubewarden-controller/Chart.yaml
charts/kubewarden-controller/chart-values.yaml
charts/kubewarden-controller/templates/opentelemetry-collector.yaml
charts/kubewarden-controller/values.yaml

feat: Add `telemetry.tracing.jaeger.tls.insecure`. 
Relates to https://github.com/kubewarden/kubewarden-controller/pull/304#issuecomment-1274366171.
```shell
helm template . --show-only templates/opentelemetry-collector.yaml \
--set telemetry.enabled=true --set telemetry.tracing.jaeger.endpoint=true \
--set telemetry.tracing.jaeger.tls.insecure=true
helm template . --show-only templates/opentelemetry-collector.yaml \
--set telemetry.enabled=true --set telemetry.tracing.jaeger.endpoint=true 
```

feat: Add `telemetry.tracing.jaeger.tls.insecure`

---

charts/kubewarden-controller/Chart.yaml
charts/kubewarden-crds/Chart.yaml
charts/kubewarden-defaults/Chart.yaml

In order to list the `kubewarden-controller` chart on downstream clusters within Rancher, this annotation needs to be removed
This annotation would only be necessary if we did not want to enable Kubewarden on downstream clusters.

Remove catalog.cattle.io/scope annotation

---

charts/kubewarden-controller/Chart.yaml

Tag a new release of the controller chart.
Given there were no changes to the CRDs and to the default deployment, the other two charts have not been touched.

Create v1.3.0-rc1 release

---

charts/kubewarden-controller/Chart.yaml
charts/kubewarden-controller/chart-values.yaml
charts/kubewarden-controller/values.yaml
charts/kubewarden-defaults/Chart.yaml
charts/kubewarden-defaults/chart-values.yaml
charts/kubewarden-defaults/values.yaml

* Add missing versions for controller and policy server container images
* Ensure the updated chart cannot be installed by mistake via `helm install`

Handle the 1.3.0-rc1 of the Kubewarden stack

---

index.yaml

This adds back `kubewarden-controller` `1.2.4`, `kubewarden-defaults` `1.2.3`. With correct digests pointing to the artifacts in the GH releases, and approximate `created` timestamps.
It bumps the index.yaml `generated` timestamp too.
Tested full Kubewarden installation with default policies active, by deploying from my fork, with:
```
helm repo add viccuad-kw https://raw.githubusercontent.com/viccuad/helm-charts/gh-pages/
vic@viccuad2 ~/suse/kw$ helm search repo viccuad-kw
NAME                                    CHART VERSION   APP VERSION     DESCRIPTION
viccuad-kw/kubewarden-controller        1.2.4           v1.3.0          A Helm chart for deploying the Kubewarden stack
viccuad-kw/kubewarden-crds              1.2.2                           A Helm chart for deploying the Kubewarden …
```

Add back `kubewarden-controller` `1.2.4`, `kubewarden-defaults` `1.2.3`

---

charts/kubewarden-controller/chart-values.yaml
charts/kubewarden-controller/templates/_helpers.tpl
charts/kubewarden-controller/templates/deployment.yaml
charts/kubewarden-controller/templates/pre-delete-hook.yaml
charts/kubewarden-controller/values.yaml
charts/kubewarden-defaults/chart-values.yaml
charts/kubewarden-defaults/templates/_helpers.tpl
charts/kubewarden-defaults/templates/policyserver-default.yaml
charts/kubewarden-defaults/values.yaml
common-values.yaml

Updates the helm charts adding a new common value used to store the container image registry to be used. This way, users can update the registry used by all the container image defined in the charts. Now helm chart values contains only the container image name and tag.
Fix #151

Separate registry and image.

---

.github/workflows/helm-chart-release.yml
charts/kubewarden-controller/Chart.yaml

Fix https://github.com/kubewarden/helm-charts/issues/155
Bump rancher-version to 2.7 in kubewarden-controller
Bump version of kubewarden-controller to 1.2.5.
Tested against a rancher 2.7 installation, it pulls kubewarden-crds correctly.

Bump to Rancher 2.7 & release

---

charts/kubewarden-defaults/chart-values.yaml
charts/kubewarden-defaults/values.yaml

Adds `longhorn-system` to the recommended policies as an excluded namespace

Exclude longhorn-system namespace in recommended policies

---

charts/kubewarden-controller/Chart.yaml
charts/kubewarden-defaults/Chart.yaml

This triggers a new release of `kubewarden-controller-1.2.6`, `kubewarden-defaults-1.2.6`.
This release will include:
https://github.com/kubewarden/helm-charts/commit/0fd760bee79d51031c512f3572eb3e0fa1c2d800 
https://github.com/kubewarden/helm-charts/commit/d37495053ecc11f14d0db3de4f19ff3e51a1d039 (release job failed for this one in the past and it stayed unreleased).
Fix incorrect `upstream-version` for kubewarden-defaults chart.
Release job for `kubewarden-controller-1.2.5` failed in the past. With this PR I'm just bumping the patch version to trigger re-release from chart-releaser, instead of deleting tag, GH Release, and amending repo index.yaml.

Release to `kubewarden-controller-1.2.6`, `kubewarden-defaults-1.2.6`, fix `upstream-version`

---

charts/kubewarden-controller/Chart.yaml

fix: Declare compat with rancher 2.6
We mistakenly took it away.

fix: Declare compat with rancher 2.6

---

charts/kubewarden-controller/Chart.yaml
charts/kubewarden-crds/Chart.yaml
charts/kubewarden-defaults/Chart.yaml

GKE clusters have a version number that embeds some GKE metadata. This metadata is added using the `-gke.<number>`.
Helm gets "confused" by this version and considers that a release candidate (due to semver rules).
Because of that, prior to this commit, attempting to deploy the Kubewarden stack on GKE resulted in this error:
```console
Error: INSTALLATION FAILED: chart requires kubeVersion: >= 1.19.0 which is incompatible with Kubernetes v1.23.8-gke.1900
```
This is now fixed

fix: ensure charts can be installed on GKE

---

charts/kubewarden-defaults/README.md
charts/kubewarden-defaults/chart-values.yaml
charts/kubewarden-defaults/templates/_helpers.tpl
charts/kubewarden-defaults/values.yaml

The helm-chart should provide a good baseline that the user can add to easily, keeping the naming so it won't break existing installations
Fixes #166

Introduce skipAdditionalNamespaces

---

.github/workflows/helm-chart-release.yml

helm push expects `helm push <path_to_chart> <registry>`, not `<registry>/chart_name`.
Fixes overly long URIs for charts in ghcr:
https://github.com/kubewarden/helm-charts/pkgs/container/charts%2Fkubewarden-controller%2Fkubewarden-controller
Tested by running the shellscript locally.
<details>
<summary>expand</summary>
```
$ bash foo.sh
+ chart_directory=release-packages
+ '[' '!' -d release-packages ']'
+ REGISTRY=ghcr.io/viccuad/test-charts
++ find release-packages -maxdepth 1 -mindepth 1 -type f
+ charts='release-packages/kubewarden-defaults-1.2.8.tgz
release-packages/kubewarden-crds-1.2.3.tgz
release-packages/kubewarden-controller-1.2.8.tgz'
+ for chart in $charts
++ helm show chart release-packages/kubewarden-defaults-1.2.8.tgz
++ yq .name
++ sed 's/"//g'
+ …
```

fix: Push to ghcr without duplicating chart name

---

charts/kubewarden-controller/Chart.yaml
charts/kubewarden-controller/app-readme.md
charts/kubewarden-controller/chart-values.yaml
charts/kubewarden-controller/templates/_helpers.tpl
charts/kubewarden-controller/templates/cert-tls.yaml
charts/kubewarden-controller/templates/configmap.yaml
charts/kubewarden-controller/templates/deployment.yaml
charts/kubewarden-controller/templates/opentelemetry-collector.yaml
charts/kubewarden-controller/templates/pre-delete-hook.yaml
charts/kubewarden-controller/templates/rbac.yaml
charts/kubewarden-controller/templates/service.yaml
charts/kubewarden-controller/templates/serviceaccount.yaml
charts/kubewarden-controller/templates/webhooks.yaml
charts/kubewarden-controller/values.yaml
charts/kubewarden-defaults/Chart.yaml
charts/kubewarden-defaults/app-readme.md
charts/kubewarden-defaults/chart-values.yaml
charts/kubewarden-defaults/templates/_helpers.tpl
charts/kubewarden-defaults/templates/allow-privileged-escalation-policy.yaml
charts/kubewarden-defaults/templates/capabilities-policy.yaml
charts/kubewarden-defaults/templates/host-namespace-policy.yaml
charts/kubewarden-defaults/templates/host-path-policy.yaml
charts/kubewarden-defaults/templates/pod-privileged-policy.yaml
charts/kubewarden-defaults/templates/policy-server-rbac.yaml
charts/kubewarden-defaults/templates/policyserver-default.yaml
charts/kubewarden-defaults/templates/user-group-policy.yaml
charts/kubewarden-defaults/values.yaml

- feat: `.Values.additionalLabels`, set default recommended labels, thanks to https://github.com/kubewarden/helm-charts/pull/176
- feat: `.Values.additionalAnnotations`
- fix: Bump controller image to `v1.4.1`: maintenance dependency bumps. The maintenance dependency bumps make the controller image pass with A image scans (even if vulnerabilities of the previous image were not affecting us).
Fix https://github.com/kubewarden/helm-charts/issues/177

Release kubewarden-controller, kubewarden-defaults `1.3.0`

---

charts/kubewarden-defaults/Chart.yaml
charts/kubewarden-defaults/chart-values.yaml
charts/kubewarden-defaults/questions.yaml
charts/kubewarden-defaults/values.yaml

Fix https://github.com/kubewarden/helm-charts/issues/172
Add questions.yaml for kubewarden-defaults.
Bump recommended policies tags.
Tested by disabling the hidden annot, and deploying the kubewarden-defaults chart/app manually (out of Kubewarden UI). These questions will show up on Kubewarden UI also.
Bumped policies are also working.
I intended to also add questions for the registry, repository and tag of the policy-server image, or at least the registry for the policy-server and policies, for air-gap use. But given that includes at least the sourcesAuthorities which are not trivial, I discarded the though to not confuse new users.

feat: Add questions.yaml to kubewarden-defaults chart

---

updatecli/updatecli.d/patch-kubewarden-controller-with-crds-update.yaml
updatecli/updatecli.d/patch-kubewarden-controller.yaml
updatecli/updatecli.d/patch-kubewarden-defaults.yaml

Updates the script used to patch release the Kubewarden charts to update the kubewarden-defaults chart annotations when a new kubewarden-crds chart is released.

fix: updates kubewarden-defaults when we have a new CRD version.

---

charts/kubewarden-controller/chart-values.yaml
charts/kubewarden-controller/templates/deployment.yaml
charts/kubewarden-controller/templates/pre-delete-hook.yaml
charts/kubewarden-controller/values.yaml

Updates the kubewarden-controller chart to allow different securityContext configurations for the controller deployment and the pre-delete-hook job
Fix #184

SecurityContext configuration

---

.github/workflows/helm-chart-release.yml

Updates the version and repository of the Helm chart releaser action to the official v1.5.0. A fork as in use because it has a fix needed by the project. As the same fix is released in the official version, the CI can use the official release again.

Update chart releaser action used to v1.5.0

---

charts/kubewarden-defaults/chart-values.yaml
charts/kubewarden-defaults/templates/policyserver-default.yaml
charts/kubewarden-defaults/values.yaml

Updates the Helm chart to make use of the latest changes in the policy server CRDs allowing users to define the "securityContext" of the workload. Therefore, this change allows users to customize the policy server "securityContext" changing the values of the Helm chart.
Fix PR makes use of the changes in the [controller](https://github.com/kubewarden/kubewarden-controller/pull/385)
Fix #191

Policy Server security configuration.

---

charts/kubewarden-defaults/chart-values.yaml
charts/kubewarden-defaults/values.yaml

Rancher v2 monitoring is deployed under the `cattle-monitoring-system` namespace.
Add this namespace to the ignore list.

fix: handle new monitoring namespace

---

.github/workflows/update-charts.yml

Downgrades updatecli version used to avoid a bug which is preventing Helm charts to be released.
This PR is a reaction for this [failing](https://github.com/kubewarden/helm-charts/actions/runs/4144658093/jobs/7167992382)

Downgrade updatecli.

---

.github/workflows/update-charts.yml

This reverts commit ec7f00eee78f3dabc53a5b46cdd6d827a2d54a8e. We can use a more recent version and still avoiding the issue. Therefore, downgrade updatecli to v2.19.0

Downgrade updatecli to v2.19.0

---

charts/kubewarden-defaults/templates/_helpers.tpl
charts/kubewarden-defaults/templates/allow-privileged-escalation-policy.yaml
charts/kubewarden-defaults/templates/capabilities-policy.yaml
charts/kubewarden-defaults/templates/host-namespace-policy.yaml
charts/kubewarden-defaults/templates/host-path-policy.yaml
charts/kubewarden-defaults/templates/pod-privileged-policy.yaml
charts/kubewarden-defaults/templates/user-group-policy.yaml

Updates the recommended policies templates to add the default registry only when the policy module is not a http URL. Thus, the module URL to use is the module defined in the values file. Otherwise, the policy module URL is  built based on the `defaultSystemRegistry` and the policy module as it before
Fix #202
```shell
make generate-values &&  helm template --set recommendedPolicies.enabled=True charts/kubewarden-defaults/ | grep "module"
module: https://susemanager.suse/pub/kubewarden/ghcr.io/kubewarden/policies/allow-privilege-escalation-psp:v0.1.11
module: ghcr.io/kubewarden/policies/capabilities-psp:v0.1.10
module: ghcr.io/kubewarden/policies/host-namespaces-psp:v0.1.3
module: ghcr.io/kubewarden/policies/hostpaths-psp:v0.1.6
module: ghcr.io/kubewarden/policies/pod-privileged:v0.2.4 …
```

Do not add default registry when policy module is a http URL.

---

.github/workflows/helm-chart-release.yml
.gitignore
Makefile
cr.yaml
scripts/generate_changelog_files.sh

Configure Helm chart releaser to add links to the Kubewarden components (controller and policy server) in the Helm charts releases.
Fix #204

Kubewarden components changelog in the chart release.

---

charts/kubewarden-defaults/Chart.yaml

Bumps kubewarden-defaults version to release the fix the issue in the recommended policies modules when the user uses http module URLs.

Bump kubewarden-defaults version to v1.5.5.

---

charts/kubewarden-crds/Chart.yaml
charts/kubewarden-defaults/Chart.yaml
updatecli/updatecli.d/major-kubewarden-update-with-crd-update.yaml
updatecli/updatecli.d/major-kubewarden-update.yaml

Changes the updatecli script to set the value of appVersion field in the Helm charts the release from the Kubewarden components. Therefore, the release candidate suffix will not be lost. This is necessary because updatecli does not have semver transformer to release candidates.

appVersion should show release candidate version.

---

charts/kubewarden-controller/chart-values.yaml
charts/kubewarden-controller/values.yaml

Maintenance bump.
Letting e2e-tests deal with it.

deps: Bump kubewarden/kubectl image to v1.25.8

---

.github/workflows/update-charts.yml

The CI script used to updated the Helm charts was not running when the version is a release candidate. This change ensures that the major and minor script will be run when the version change is a release candidate bump

Run update CI on prerelease version bump.

---

charts/kubewarden-controller/templates/rbac.yaml

Reduce the privileges granted to the ServiceAccount used by the kubewarden-controller.
This is a propagation of the fixes done inside of https://github.com/kubewarden/kubewarden-controller/pull/429

fix: reduce the scope of kubewarden-controller Service Account

---

.github/workflows/update-charts.yml

The script used to detect CRDs update can replace the cluster admission policies CRD definition by the admission policy one. Due the file name filter used in the find command. This fixes the issue adding a "_" in front of the name pattern.

Fix script to detect CRDs update.

---

.github/workflows/update-charts.yml

The script used to detect CRDs update can replace the cluster admission policies CRD definition by the admission policy one. Due the file name filter used in the find command. This fixes the issue adding a "_" in front of the name pattern.

Fix script to detect CRDs update in major/minor updates.

---

charts/kubewarden-defaults/Chart.yaml

I would like to have a new release of the kubewarden-defaults chart that includes this fix https://github.com/kubewarden/helm-charts/pull/223

Create new RC for the defaults chart

---

.github/workflows/e2e-tests.yml

Error in our runs: https://github.com/kubewarden/helm-charts/actions/runs/4699099020/jobs/8332177916#step:4:16
Fix for: https://github.com/kubewarden/kubewarden-end-to-end-tests/issues/57
```bash
~ echo "controller-image-repository=$(helm show values charts/kubewarden-controller | yqgo  '.common.cattle.systemDefaultRegistry+"/"+.image.repository')"
controller-image-repository=null
~ echo "controller-image-repository=$(helm show values charts/kubewarden-controller | yqgo  '.common.cattle.systemDefaultRegistry + "/" + .image.repository')"
controller-image-repository=ghcr.io/kubewarden/kubewarden-controller
```

Fix yq concatenation

---

charts/kubewarden-defaults/chart-values.yaml
charts/kubewarden-defaults/templates/policyserver-default.yaml
charts/kubewarden-defaults/values.yaml

Relates to https://github.com/kubewarden/ui/issues/287
Now the controller is the one in charge of configuring PolicyServers with telemetry enabled.
Tested in the controller side.

fix!: Remove `.Values.telemetry` from kubewarden-defaults

---

charts/kubewarden-controller/Chart.yaml

Bumps the kubewarden-controller chart version to release the post-install hook to ensure that the controller will have the OTEL sidecar when telemetry is enable.

kubewarden-controller release v1.5.3

---

charts/kubewarden-controller/chart-values.yaml
charts/kubewarden-controller/templates/_helpers.tpl
charts/kubewarden-controller/templates/cronjob.yaml
charts/kubewarden-controller/templates/rbac.yaml
charts/kubewarden-controller/templates/serviceaccount.yaml
charts/kubewarden-controller/values.yaml
charts/kubewarden-crds/templates/admissionpolicies.yaml
charts/kubewarden-crds/templates/clusteradmissionpolicies.yaml

Partially implements https://github.com/kubewarden/helm-charts/issues/237
Missing: shipping CRDs and depending on them.
- Add ServiceAccount and ClusterRole
- Add cronjob.yaml templat
- Add new experiemental values.
Follow https://github.com/kubewarden/audit-scanner/blob/main/CONTRIBUTING.md.
Once you have Kubewarden and all CRDs installed, checkout the `feat-audit` branch on kubewarden/helm-charts,
and do:
```
helm upgrade -i --wait --namespace kubewarden \
--create-namespace kubewarden-controller ./kubewarden-controller \
--set image.tag=latest-feat-audit --set image.repository=viccuad/kubewarden-controller
```
Note: PR against `feat-audit` branch.
Missing shipping and depending on CRDs.
Missing skipping namespaces.

feat: Add audit-scanner as experimental feature

---

.github/workflows/e2e-tests.yml
charts/kubewarden-controller/chart-values.yaml
charts/kubewarden-controller/templates/_helpers.tpl
charts/kubewarden-controller/templates/deployment.yaml
charts/kubewarden-controller/values.yaml
charts/kubewarden-defaults/chart-values.yaml
charts/kubewarden-defaults/templates/_helpers.tpl
charts/kubewarden-defaults/templates/allow-privileged-escalation-policy.yaml
charts/kubewarden-defaults/templates/capabilities-policy.yaml
charts/kubewarden-defaults/templates/host-namespace-policy.yaml
charts/kubewarden-defaults/templates/host-path-policy.yaml
charts/kubewarden-defaults/templates/pod-privileged-policy.yaml
charts/kubewarden-defaults/templates/policyserver-default.yaml
charts/kubewarden-defaults/templates/user-group-policy.yaml
charts/kubewarden-defaults/values.yaml
common-values.yaml

Updates the global configuration values used by all the charts from common.cattle.* to global.cattle.* to follow the Rancher standards.
Fix #241

fix!: rename common.cattle.* to global.cattle.*

---

README.md
index.yaml

This PR revert the latest two commits which released by accident the `kubewarden-crds` helm chart.

Revert acidental  kubewarden-crds chart release

---

charts/kubewarden-controller/Chart.yaml
charts/kubewarden-crds/Chart.yaml
charts/kubewarden-defaults/Chart.yaml

Reverts the `kubewarden-crds` chart version form 1.4.0 back to 1.3.1. The version was bumped by accident during a feature branch merge.

fix: revert accidental kubewarden-crds version bump.

---

charts/kubewarden-controller/chart-values.yaml
charts/kubewarden-controller/values.yaml

Relates to https://github.com/kubewarden/kubewarden-controller/issues/465
Bump to latest from https://github.com/kubewarden/rancher-kubectl-builder/pkgs/container/kubectl.
Default to audit-scanner disabled.
E2E tests.

deps: Bump kubectl image to 1.26.6

---

Makefile
charts/kubewarden-controller/chart-values.yaml
charts/kubewarden-controller/templates/_helpers.tpl
charts/kubewarden-controller/templates/cronjob.yaml
charts/kubewarden-controller/values.yaml
charts/kubewarden-defaults/chart-values.yaml
charts/kubewarden-defaults/templates/_helpers.tpl
charts/kubewarden-defaults/values.yaml
common-values.yaml

Both kubewarden-controller and kubewarden-defaults charts uses the skipNamespaces values. Therefore, the field now lives under the global values. The kubewarden-defaults helper template has also been update to fetch the values from the new location.
Change the audit scanner CronJob definition to build the command adding the flags to skip the system namespaces.
Fix #254
This PR is **blocked** by the merge of https://github.com/kubewarden/audit-scanner/pull/53

Audit scanner skip system namespaces

---

charts/kubewarden-controller/chart-values.yaml
charts/kubewarden-controller/values.yaml

Updates the kubewarden-controller to enable the audit scanner component by default.

feat: audit scanner enable by default.

---

charts/kubewarden-controller/chart-values.yaml
charts/kubewarden-controller/templates/_helpers.tpl
charts/kubewarden-controller/templates/audit-scanner.yaml
charts/kubewarden-controller/values.yaml

Partial implementation of https://github.com/kubewarden/audit-scanner/issues/64
Needs an audit-scanner image with https://github.com/kubewarden/audit-scanner/pull/75
This is done with a volumeMount. The `policy-server-root-ca` is created by the kubewarden-controller deployment, but only when there is a policy-server. This means that the first installation of kubewarden-controller chart will deploy an audit-scanner cronjob that will continously fail, until there's a policy-server instantiated (normally when one installs the kubewarden-default chart).
This doesn't need to be this way, we can change the kubewarden-controller reconcile loop so it creates the ca secret without needing a policy-server first.
Tested locally, needs https://github.com/kubewarden/audit-scanner/pull/75

feat: Consume policy-server-root-ca Secret in auditScanner Cronjob

---

charts/kubewarden-controller/templates/NOTES.txt
charts/kubewarden-crds/templates/NOTES.txt
charts/kubewarden-defaults/templates/NOTES.txt

Attempt to improve NOTES.txt that show on installation/upgrade.
While it isn't easy to summarize Kubewarden, we could do better here.

docs: Improve NOTES.txt

---

artifacthub-repo.yml
scripts/extract_images.sh
scripts/generate_changelog_files.sh

Fix https://github.com/kubewarden/helm-charts/issues/267
- build: Ignore prereleases on artifacthub
- fix: Don't generate imagelist.txt for kubewarden-crds
- feat: Consume changelogs from audit-scanner GH releases
Tested from my fork.
See that https://artifacthub.io/packages/helm/viccuad-kw/kubewarden-controller doesn't contain -rc releases.

build: Ignore prereleases on artifacthub 

---

charts/kubewarden-controller/chart-values.yaml
charts/kubewarden-controller/templates/deployment.yaml
charts/kubewarden-controller/values.yaml

Adds a new value to allow user to define the number of replicas used to run the Kubewarden controller.
Fix https://github.com/kubewarden/helm-charts/issues/266

feat: allow set controller replicas count.

---

.github/workflows/update-charts.yml

The step used to download the CRDs from the audit scanner release was using a variable defined in another step. Fix that by using the proper variable.

fix: refer to audit scanner repository

---

updatecli/scripts/install_crds.sh

Updates the script used to install the CRDs to add a if statement in the files updated adding a if statement to allow users to skip CRDs installation based on the `installPolicyReportCRDs` configuration.

fix: allow user skip reports CRDs installation.

---

.idea/.gitignore
charts/kubewarden-controller/chart-values.yaml
charts/kubewarden-controller/templates/_helpers.tpl
charts/kubewarden-controller/values.yaml

After using audit-scanner, deployed using Helm chart `kubewarden-controller` 1.6.0-rc2, I've noticed that there are a couple of parameters that are available in `audit-scanner` binary that unfortunately we can't use during the chart installation. This commit tries to improve that.
Please let me know if you agree with this change or if this isn't at all aligned with the vision that you have for `audit-scanner`. Thank you!

Allows more customisation to audit-scanner

---

.github/workflows/ci.yaml
.github/workflows/e2e-tests.yml
.github/workflows/helm-chart-release.yml
.github/workflows/update-charts.yml
renovate.json

Reference GH actions by shasum, plus leave a comment about the full version being referenced by the checksum

chore(deps): be explicit about GH actions

---

charts/kubewarden-crds/templates/clusterpolicyreports.yaml
charts/kubewarden-crds/templates/policyreports.yaml

In the Rancher manager environment, an issue arises during updates of the kubewarden-crds chart where the "installPolicyReportCRDs" configuration is sometimes set to "null." This results in problems as the CRDs, which should be installed by default, are not deployed. To address this issue, we've enhanced the conditional logic to install the CRDs when the flag is explicitly set to true or when it is missing altogether.
Fix https://github.com/kubewarden/kubewarden-controller/issues/515

fix: Ensure installation of PolicyReport CRDs if value is missing or set to "null"

---

updatecli/scripts/install_crds.sh

The install_crds.sh script used by updatecli to install new version of     the CRDs is missing a logic clause in the if statement to check if the  policy report CRDs should be installed. This commit fixed that by adding the missing "or" logic.

fix: wrong if statement to install policy report CRDs.

---

charts/kubewarden-controller/Chart.yaml
charts/kubewarden-crds/Chart.yaml
charts/kubewarden-defaults/Chart.yaml

This means each chart gets a bump of their `version`. Then, we consume that change on the annotations, for
catalog.cattle.io/auto-install
catalog.cattle.io/upstream-version
Note, no change to images was done, hence `appVersion` stays as it was.
CI

build: Bump chart `version` to -rc4

---

.github/workflows/update-charts.yml

The CI step to check if there is some CRDs update is doing the same done in the script to install the CRDs. Therefore, the CI could detect an update that does not exist. This commit fixes that by updating the `sed` commands used to manipulate some files.

fix: CI should do the same changes in the policy reporter.

---

charts/kubewarden-defaults/templates/NOTES.txt

Inform the user about the policies that have been installed by the kubewarden-defaults chart only when the `recommendedPolicies.enabled` is set to `True` (which is not the default).
Also, make sure the user knows the default policies are deployed using the `monitor` mode.

fix: kubewarden defaults post installation message

---

charts/kubewarden-defaults/Chart.yaml

Perform a new release of the kubewarden-defaults chart to include https://github.com/kubewarden/helm-charts/pull/299

chore: bump version of kubewarden-defaults

---

charts/kubewarden-controller/templates/webhooks.yaml

Add policyserver validtaing webhook to the controller chart.
related to: https://github.com/kubewarden/kubewarden-controller/pull/530
Tested against a local cluster

feat: add PolicyServer validating webhook

---

.github/workflows/update-charts.yml
updatecli/scripts/install_crds.sh

Right now, the `update_crds` acts as if it had tar.gz for both
controller and audit-scanner crds. This makes it fail if the dispatched
job is only for 1 of those and not the other.
Fixes automated patch version PRs.
See for example how both of these jobs fail:
- https://github.com/kubewarden/helm-charts/actions/runs/6323127363/attempts/1 -> missing crds tar.gz for the audit-scanner, as this is the controller.
- https://github.com/kubewarden/helm-charts/actions/runs/6324807827 -> missing crds tar.gz for the controller, as this is the audit-scanner.
Untested.
Relates to https://github.com/kubewarden/kubewarden-controller/issues/534.

ci: Make update_crds step conditional 

---

renovate.json

On #294, the bot bumped of policy-reporter-ui, where it got bumped to v1.15.1. Turns out that 1.15.1 tag is 2 years old, and looks like a mistake on tagging, as it is between 0.15.0 and 0.15.1 in the timeline. See: https://github.com/orgs/kyverno/packages/container/policy-reporter-ui/10126783?tag=1.15.1
Relates to https://github.com/kubewarden/helm-charts/issues/311.
Not tested. We should be able to notice it's working once we merge and retrigger renovate bot, not getting an update for the image.

ci: Ignore policy-reporter-ui image 1.15.1

---

charts/kubewarden-defaults/chart-values.yaml
charts/kubewarden-defaults/templates/policyserver-default.yaml
charts/kubewarden-defaults/values.yaml

Relates to https://github.com/kubewarden/helm-charts/issues/310.
Setting this to true will add the necesary `KUBEWARDEN_LOG_FMT` env var to the default PolicyServer, so it outputs telemetry in OTLP format.
This is needed because the kubewarden controller doesn't take care of reconciling this env var anymore, allowing users to fine tune it.
For this commit's case, the default PolicyServer, we are fine keeping the behaviour as it is.
Note that this is not backwards compatible, as
`.Values.policyServer.telemetry` defaults to `false`.
To be tested together with a new controller image.

feat: Add .Values.policyServer.telemetry to kubewarden-defaults

---

charts/kubewarden-controller/chart-values.yaml
charts/kubewarden-controller/templates/deployment.yaml
charts/kubewarden-controller/templates/opentelemetry-collector.yaml
charts/kubewarden-controller/templates/post-install-hook.yaml
charts/kubewarden-controller/templates/service.yaml
charts/kubewarden-controller/values.yaml
charts/kubewarden-defaults/chart-values.yaml
charts/kubewarden-defaults/templates/policyserver-default.yaml
charts/kubewarden-defaults/values.yaml

Relates to https://github.com/kubewarden/helm-charts/issues/310.
Now the kubewarden-controller image reconciles configuration of both
tracing and telemetry for PolicyServers. Configure it so.
Consume `telemetry.metrics.enabled` and `telemetry.tracing.enabled` for
the rest of cases, making configuration more fine graded. This should
result in cleaner OTLP collector and sidecar logs.
E2E tests.

feat!: Fine-grain config for metrics and tracing

---

charts/kubewarden-controller/questions.yaml

Updates the port number in the default value for the `telemetry.tracing.jaeger.endpoint` question, as the otlp port needs to be `4317`.
https://opentelemetry.io/blog/2023/jaeger-exporter-collector-migration/

Update jaeger endpoint port in questions default value

---

charts/kubewarden-controller/Chart.yaml
charts/kubewarden-controller/chart-values.yaml
charts/kubewarden-controller/values.yaml

This a redo of https://github.com/kubewarden/helm-charts/pull/343.
That one didn't end up in a created release, because it was failing CI for `make check-generate-values` and `make generate-changelogs`.
We didn't realize, because CI doesn't run automatically for GH dispatches from bots, see: https://github.com/kubewarden/helm-charts/issues/324
The workaround in the case of bot PRs is to close and reopen the PR. That way the CI runs.
CI

Release kubewarden-controller 2.0.2

---

Makefile
scripts/check-common-values.sh

This target diffs the contents of `./common-values.yaml` and `charts/*/chart-values.yaml` for the `global` key.
This is analogous to what `make check-generated-values` does, but without calling `make generated-values`, nor having an interim `./charts/foo/chart-values.yaml` file per chart.
This new target is intended to substitute `make check-generated-values` and to drop the `chart-values.yaml`. This will simplify contributions and automation.
Edit common-values.yaml, for example adding a `.global.foo` key with value `bar`:
```console
$ make check-common-values
8d7
<       "foo": "bar",
kubewaden-controller values.yaml diverges from common-values.yaml
make: *** [Makefile:23: check-common-values] Error 1
```
On unchanged, correct chart values.yaml, it succeeds.

feat: Add `make check-common-values` target

---

charts/kubewarden-controller/templates/_helpers.tpl
charts/kubewarden-controller/templates/audit-scanner.yaml
charts/kubewarden-controller/templates/deployment.yaml
charts/kubewarden-controller/templates/pre-delete-hook.yaml

Set imagePullSecrets for pre-delete-hook image.
The `kubewarden-controller` chart now accepts both:
`--set 'imagePullSecrets[0]=my-secret'`
`--set 'imagePullSecrets[0].name=my-secret'`

fix: Add imagePullSecrets for pre-delete-hook-image, support both with name or not

---

charts/kubewarden-controller/chart-values.yaml
charts/kubewarden-controller/values.yaml

The Policy Reporter UI logs tab shows logs for enabled targets. Possible targets:
https://kyverno.github.io/policy-reporter/core/targets/
This is configured by enabling the logs view, and setting `policy-reporter.ui.sources[]` value.
The log tab will be empty by default though, which can be disorienting. Disabling it.
Tested locally.

fix: Disable logs tab on policy-reporter UI

---

charts/kubewarden-controller/chart-values.yaml
charts/kubewarden-controller/templates/_helpers.tpl
charts/kubewarden-controller/values.yaml

Fix [#107](https://github.com/kubewarden/audit-scanner/issues/107)
As required by https://github.com/kubewarden/audit-scanner/issues/107, this commit adds the new flag - `store` - to the `kuberwarden-controller` Helm chart.
Tested locally using `helm template charts/kubewarden-controller`

feat: exposes `store` flag from `audit-scanner`

---

charts/kubewarden-defaults/chart-values.yaml
charts/kubewarden-defaults/templates/policyserver-default.yaml
charts/kubewarden-defaults/values.yaml

Ability configure the `securityContexts` from the PolicyServer Custom resource through the kubewarden-defaults Helm chart
I also found that the `{{- end }}` directive for `{{- if .Values.global.policyServer.default.enabled }}` was being closed too soon, making some values of the definition leak even if the policyServer is disabled
The format follows the CRD definition https://docs.kubewarden.io/operator-manual/CRDs#policyserversecurity
1. Go to the [chart-values.yaml](https://github.com/kubewarden/helm-charts/blob/main/charts/kubewarden-defaults/chart-values.yaml) and replace
```yaml
securityContexts: {}
```
with
```yaml
securityContexts:
pod:
runAsNonRoot: true
```
2. Execute on the root of the repo
```shell
make …
```

feat: Include `securityContexts` Kubewarden-defaults Helm chart for Policy Servers

---

charts/kubewarden-defaults/templates/allow-privileged-escalation-policy.yaml
charts/kubewarden-defaults/templates/user-group-policy.yaml

Updates the mutating policies to target pod resources only. This avoid reconciliation issues of higher level resources managed by other controllers.
Fix https://github.com/kubewarden/helm-charts/issues/374

fix: mutating policies targets pod only.

---

charts/kubewarden-controller/Chart.yaml
charts/kubewarden-controller/chart-values.yaml
charts/kubewarden-controller/values.yaml

Image `kubewarden-controller:v1.10.1` contains a bump of `github.com/opencontainers/runc` to `v1.1.12`. runc is a dev dependency used in integration tests, and while we are not affected, previous versions are vulnerable to CVE-2024-21626.
This image bump makes the image scan clean.
CI

chore(deps): Bump controller image to `v1.10.1`, release kubewarden-controller `2.0.7`

---

.github/workflows/helm-chart-release.yml

Relates to  https://github.com/kubewarden/helm-charts/issues/362
Leftover from https://github.com/kubewarden/helm-charts/issues/362
CI. This should make the release workflow work again in main (even if chart-releaser correctly sees there's nothing new to release).

refactor: Drop `make check-generated-values`, use `make check-common-values`

---

charts/kubewarden-controller/Chart.yaml
charts/kubewarden-controller/values.yaml

For big clusters with big (Cluster)PolicyReports, it is cost-prohibitive to print them as `info` logs in the auditScanner Jobs.
Change `auditScanner.outputScan` as opt-in, with false as default.
Bump kubewarden-controller chart to version `2.0.8`.
CI
This is a breaking change. I have considered shipping it as a minor release instead and I am undecided. Nevertheless, it should be documented in changelog and notified.

fix!: Default to auditScanner.outputScan=false

---

updatecli/updatecli.d/major-kubewarden-update.yaml
updatecli/updatecli.d/prerelease-kubewarden-update.yaml

There are two updatecli yaml files missing the `targets` field. Thus, the execution failed because all the update actions that should be under `targets` are children of the `conditions` field. This commit that adding the `targets` field.
This commit also fixes some warning messages from updatecli about the keys used to find the fields in the Helm chart yaml files.
This fix is required to tag `v1.11.0-rc1`. https://github.com/kubewarden/kubewarden-controller/issues/642

fix(ci): fix broken updatecli yaml files.

---

charts/kubewarden-controller/values.yaml

Increase the amount of memory requested by the controller Pod and its limit.
Data is based on https://github.com/kubewarden/helm-charts/issues/157
Fixes https://github.com/kubewarden/helm-charts/issues/157

raise controller memory limits

---

charts/kubewarden-controller/templates/_helpers.tpl
charts/kubewarden-controller/values.yaml

The container command is an array of strings. The `--disable-store` flag value passed is `false` which fails. Because it is unmarshaled as boolean. To fix that, the helper code to build the command must quote the boolean value
The memory resource configuration for the audit scanner is wrong. The limit is less then the requested amount. This  commit fixed that by inverting the quantities.
Fix #390

fix: invalid audit scanner container command.

---

charts/kubewarden-controller/Chart.yaml
charts/kubewarden-crds/Chart.yaml
charts/kubewarden-defaults/Chart.yaml

Updates the appVersion of the kubewarden-crds chart to keep it in sync with the other charts. The version is now v1.11.0-rc3. The chart version also needs to be updated to release the chart.
Fix #395

chore: kubewarden-crds version bump.

---

.github/workflows/update-charts.yml
updatecli/scripts/install_crds.sh

Fix https://github.com/kubewarden/helm-charts/issues/307
Changes: 
- Add UI inputs when workflow triggered as `workflow_dispatch`.
Given that the values can come from `repository_dispatch` (other repos) or `workflow_dispatch` (UI button), add a new `setvariables` job, that sets its job outputs to the corresponding values obtained from the payload of the repository_dispatch or from the inputs of the workflow_dispatch.
It is needed to use job outputs as is the only way to pass values between jobs, as jobs are run in their own VM instances and don't share the env.
Make the following jobs depend on it with `needs: setvariables`.
The javascript script from actions/github-script cannot read job outputs. Hence, add a step that reads the `needs.setvariables.outputs` and creates env vars. Consume …

ci: Add UI inputs for `Update helm charts` job, refactor and drop need for `crds_asset_id` 

---

updatecli/updatecli.d/major-kubewarden-update.yaml
updatecli/updatecli.d/prerelease-kubewarden-update.yaml

The CRDs chart was being updated only when there was some CRDs change. However, the `appVersion` should be kept in sync among all the three repositories. Therefore, the updatecli script to perform the update with no CRD change should also bump the `appVersion` in the `kubewarden-crds` chart
Fix #398

fix(ci): update crds chart in any major/minor update.

---

charts/kubewarden-controller/templates/post-install-hook.yaml

Part of  https://github.com/kubewarden/helm-charts/issues/408
Depends on audit-scanner 1.11.0-rc6 shipping https://github.com/kubewarden/audit-scanner/pull/231.
This job deletes all pre 1.11 (Cluster)PolicyReports, by matching and deleting those reports that lack the label
`kubewarden.io/policyreport-version`.
Tested locally by running the kubectl command, helm hook untested.

feat: Add delete-pre-1.11-policyreports-job to postinstall hook

---

.github/workflows/update-dependencies.yaml
charts/kubewarden-controller/values.yaml
charts/kubewarden-defaults/templates/allow-privileged-escalation-policy.yaml
charts/kubewarden-defaults/templates/capabilities-policy.yaml
charts/kubewarden-defaults/templates/host-namespace-policy.yaml
charts/kubewarden-defaults/templates/host-path-policy.yaml
charts/kubewarden-defaults/templates/pod-privileged-policy.yaml
charts/kubewarden-defaults/templates/user-group-policy.yaml
charts/kubewarden-defaults/values.yaml
renovate.json
updatecli/DEVELOP.md
updatecli/updatecli.d/major-kubewarden-update.yaml
updatecli/updatecli.d/patch-kubewarden-controller-with-crds-update.yaml
updatecli/updatecli.d/patch-kubewarden-controller.yaml
updatecli/updatecli.d/patch-kubewarden-defaults.yaml
updatecli/updatecli.d/prerelease-kubewarden-update-with-crd-update.yaml
updatecli/updatecli.d/prerelease-kubewarden-update.yaml
updatecli/updatecli.d/update-deps.yaml

Fix https://github.com/kubewarden/helm-charts/issues/388
Add job that checks the policies and kubectl image tags every week,
and opens a PR if there's any bump needed.
Tested updatecli part locally with:
```UPDATECLI_GITHUB_OWNER=viccuad updatecli diff \
--config updatecli/updatecli.d/update-deps.yaml \
--values updatecli/values.yaml
```
Tested `make generate-policies-file generate-images-file`, everything works for airgap scripts.
Tested in my fork:
https://github.com/viccuad/helm-charts/actions/runs/8393105846/job/22987348660
https://github.com/viccuad/helm-charts/pull/2
Should wait for merge until 1.11 is released.

Add job to update policies and kubectl image

---

charts/kubewarden-crds/templates/policyservers.yaml
charts/kubewarden-defaults/values.yaml

Adds PolicyServer limits/requests values to kubewarden-default and generated CRDs with the new fields.
Related to: https://github.com/kubewarden/kubewarden-controller/issues/710

feat: add limits and requests to PolicyServer

---

charts/kubewarden-defaults/templates/policyserver-default.yaml

Somehow something went wrong in the `policyserver-default` template when merging PRs, ending up with a broken template.
The CI didn't catch it so we went forward with the PR. 
Note:
We are investigating why the CI is not running the PRs helm charts, but it runs e2e tests against the already released tags.
I've re-tested the chart manually by installing it on a local cluster.

fix: policyserver-default template

---

charts/kubewarden-controller/templates/deployment.yaml
charts/kubewarden-controller/values.yaml

Exposes kubewarden-controller logLevel value, setting the `--zap-log-level` flag.
Fixes https://github.com/kubewarden/kubewarden-controller/issues/693

feat: expose kubewarden-controller logLevel value

---

charts/kubewarden-defaults/questions.yaml
charts/kubewarden-defaults/templates/allow-privileged-escalation-policy.yaml
charts/kubewarden-defaults/templates/capabilities-policy.yaml
charts/kubewarden-defaults/templates/host-namespace-policy.yaml
charts/kubewarden-defaults/templates/host-path-policy.yaml
charts/kubewarden-defaults/templates/pod-privileged-policy.yaml
charts/kubewarden-defaults/templates/user-group-policy.yaml
charts/kubewarden-defaults/values.yaml

Add default policies questions.yaml into the chart questions, so if they are configured via chart, one sees their settings questions.
This is an alternative to https://github.com/kubewarden/helm-charts/pull/426.
This is possible for all policies besides those using `type: sequence[`, as that isn't ported to rancher/dashboard yet. Opened https://github.com/rancher/dashboard/issues/10826, https://github.com/rancher/dashboard/issues/10827 for that. For those, I have left the questions commented and they aren't customizable, as `type: yaml` is buggy for now (see https://github.com/rancher/dashboard/issues/10814).
Fixes https://github.com/kubewarden/helm-charts/pull/426
Tested by installing a repo consuming this pr.
If this is merged, the UI could redirect to the kubewarden-defaults chart …

feat: Expose policy settings via chart questions

---

charts/kubewarden-defaults/Chart.yaml

Bump kubewarden-defaults version to **2.0.0-rc4** because of the following breaking changes:
Changes to values.yaml under `recommendedPolicies`. All policies now have `recommendedPolicies.Foo.settings` for our preferred settings, instead of having them set in the templates.

build: Bump kubewarden-defaults version to 2.0.0-rc4

---

charts/kubewarden-controller/templates/rbac.yaml

To clean up old policy reports created by audit scanner, it needs permissions to delete a collection of the reports. Requiring a change in the scanner role adding the "deletecollection" verb.
Fix https://github.com/kubewarden/audit-scanner/issues/263

fix: audit scanner delete collection permission.

---

charts/kubewarden-controller/questions.yaml
charts/kubewarden-controller/templates/_helpers.tpl
charts/kubewarden-controller/values.yaml

Update the helm kubewarden-controller to expose the new flags of the audit-scanner

feat: expose new audit-scanner flags

---

charts/kubewarden-controller/Chart.yaml
charts/kubewarden-crds/Chart.yaml
charts/kubewarden-defaults/Chart.yaml

Automation overwrote the changes we did to https://github.com/kubewarden/helm-charts/pull/454
This brings back the right values.
Note well: I've deleted all the tags and the GitHub release objects created by the automation.

fix release numbers

---

charts/kubewarden-defaults/templates/policyserver-default.yaml

Updates the default policy server to use domain qualified finalizer and follow the change in the controller as well.
Related to https://github.com/kubewarden/kubewarden-controller/issues/728
Manual testing

fix: use domain qualified finalizers in the default policy server.

---

charts/kubewarden-controller/templates/audit-scanner.yaml
charts/kubewarden-controller/templates/deployment.yaml
charts/kubewarden-controller/values.yaml
charts/kubewarden-defaults/templates/_helpers.tpl
charts/kubewarden-defaults/templates/policyserver-default.yaml
charts/kubewarden-defaults/values.yaml
common-values.yaml

Add two new fields in the global values used by the Kubewarden helm charts to  add affinity and tolerations configuration in all the Helm charts. 
Fix https://github.com/kubewarden/kubewarden-controller/issues/756

feat: add tolerations and affinity in the global values 

---

charts/kubewarden-controller/templates/deployment.yaml
charts/kubewarden-controller/values.yaml
charts/kubewarden-defaults/templates/policyserver-default.yaml
charts/kubewarden-defaults/values.yaml
common-values.yaml

The Kubewarden controller does not have the CLI flag to allow users to define the name of the default policy server name. Therefore, the helm chart does not need that configuration anymore. Thus, this commit removes the global values to configure that in the kubewarden-controller and kubewarden-default charts.
Fix  https://github.com/kubewarden/kubewarden-controller/issues/809

fix!: remove the default policy server name.

---

charts/kubewarden-controller/templates/opentelemetry-collector.yaml

This reverts commit 05a6207ae18d7fce5fc96c93491e119b9254bd48.
This revert ought to fix the jaeger helm chart install error:
```
jaeger.jaegertracing.io/my-open-telemetry created
Error: UPGRADE FAILED: failed to create resource: admission webhook "mopentelemetrycollectorbeta.kb.io" denied the request: json: cannot unmarshal string into Go struct field OpenTelemetryCollectorSpec.spec.config of type v1beta1.Config
```
There seems to be incompatibilities between latest jaeger-operator-2.54.0 (from 2024-06) and latest opentelemetry-operator-0.64.4.
The latest opentelemetry-operator chart includes the operator image 0.103.0 but has not yet consumed 0.104.0, which performs the migrationg to OpentelemetryCollector apiVersion `opentelemetry.io/v1beta1`.
Fix #XXX
To test this pull request, you can …

Revert "deps: Bump OpenTelemetryCollector to v1beta1 (#479)"

---

charts/kubewarden-controller/templates/opentelemetry-collector.yaml

This removes warning:
```
W0725 16:45:37.530588   37879 warnings.go:70] Collector config
spec.config has null objects: processors.batch:,
receivers.otlp.protocols.grpc:. For compatibility with other tooling,
such as kustomize and kubectl edit, it is recommended to use empty
objects e.g. batch: {}.
```
Tested manually.

chore: Correctly terminate null objects in collector template

---

charts/kubewarden-defaults/values.yaml

The userGroup policy shouldn't validate the container image configuration to check for the user being run there, as that is too stringent.
Coincidentally, this ameliorates https://github.com/kubewarden/user-group-psp-policy/issues/93
CI

fix: Use correct default settings for userGroup policy

---

charts/kubewarden-defaults/values.schema.json

Breaking some automations while passing parameters from one file another. Original variable type should be corrected. Otherwise facing unnecessary issues. 
Error: INSTALLATION FAILED: values don't meet the specifications of the schema(s) in the following chart(s):
kubewarden-defaults: policyServer.minAvailable: Invalid type. Expected: string, given: integer

fix: values.schema.json PDB variable type

---

charts/kubewarden-defaults/values.schema.json
charts/kubewarden-defaults/values.yaml

Relates to https://github.com/kubewarden/helm-charts/pull/505
Revert to using string for `minAvailable, maxUnavailable`.
Fix the schema to only accept either `minAvailable` only, `maxUnavailable` only, or neither (XOR).
Tested by consuming the following values:
```
recommendedPolicies:
enabled: True
defaultPolicyMode: monitor
policyServer:
minAvailable: "20%"
maxUnavailable: "1"
```
Which results on:
```
$ helm lint ./charts/kubewarden-defaults --values myvalues.yaml
==> Linting ./charts/kubewarden-defaults
[ERROR] values.yaml: - policyServer: Must validate at least one schema (anyOf)
- policyServer: Must validate one and only one schema (oneOf)
[ERROR] templates/: values don't meet the specifications of the schema(s) in the following chart(s):
kubewarden-defaults:
- policyServer: Must …
```

fix: schema with XOR for minAvailable, maxUnavailable

---

charts/kubewarden-controller/templates/webhooks.yaml

Create and use ECDSA private keys when generating CA and leaf certificates.
The same was done in the controller in  https://github.com/kubewarden/kubewarden-controller/pull/866

fix: generate and use ecdsa private keys

---

charts/kubewarden-controller/templates/webhooks.yaml

The validity duration for the root CA and other certificate generated in the webhooks.yaml are inverted. In the current code, the root CA expiration is less than the certificate used by the controller, which is signed by the root CA. However, the root CA validity should be 10 years (3650 days) and the certificate used by the controller webserver should be 1 year (365 days). This commit fixes the issue by inverting the validity duration in both certificates.
Related to https://github.com/kubewarden/kubewarden-controller/issues/7

fix: wrong certificates validity duration

---

charts/kubewarden-controller/templates/rbac.yaml
charts/kubewarden-controller/templates/webhooks.yaml
charts/kubewarden-crds/templates/admissionpolicygroups.yaml
charts/kubewarden-crds/templates/clusteradmissionpolicygroups.yaml
charts/kubewarden-crds/templates/policyservers.yaml

Updates the Helm charts to have the files required by the controller to be able to reconcile policy group types.
Fix https://github.com/kubewarden/kubewarden-controller/issues/857

Policy group files

---

charts/kubewarden-controller/templates/post-install-hook.yaml

With long enough release names (such as the ones used by Rancher), the Job metadata.name goes over the 63 chars.
Fix 
```
Error: failed post-install: warning: Hook post-install kubewarden-controller/templates/post-install-hook.yaml failed: 1 error occurred:
* Job.batch "rancher-kubewarden-controller-delete-pre-1-17-webhook-server-cert" is invalid: spec.template.labels: Invalid value: "rancher-kubewarden-controller-delete-pre-1-17-webhook-server-cert": must be no more than 63 characters
```

chore: Shorten `del-pre-1-17-webhook-srv-cert` hook name

---

charts/kubewarden-controller/templates/audit-scanner.yaml

Fix https://github.com/kubewarden/helm-charts/issues/524:
```
MountVolume.SetUp failed for volume "kubewarden-ca" : secret "kuebewarden-ca" not found
```
on Audit scanner runs.

fix: Fix typo on audit-scanner CronJob

---

charts/kubewarden-controller/templates/webhooks.yaml

Updates the webhooks.yaml template to set a default value "" to the old CA certificate when it's missing. This can happen because the empty value in the secret is removed during the upgrade. Therefore, in a future upgrade the b64enc function fails because the value is nil.
Fix https://github.com/kubewarden/helm-charts/issues/523

fix: set default value for old CA field when missing.

---

.github/workflows/ci.yaml
charts/kubewarden-controller/tests/webhooks_existing_certifcates_test.yaml
charts/kubewarden-controller/tests/webhooks_test.yaml

test: add kubewarden-controller webhooks unit test

---

charts/kubewarden-controller/templates/rbac.yaml

The service account used by the audit-scanner process must be able to access group policies (both cluster and namespaced ones).
I've tested the fix locally and it works.

fix: allow audit-scanner to scan group policies

---

charts/kubewarden-controller/values.yaml

v1.17.1 doesn't exist yet, it was incorrectly bumped by the update-cli automation PR.
After merging this, the release for kubewarden-controller version 3.0.1 should succeed.

deps: Correctly consume audit-scanner v1.17.0

---

charts/kubewarden-defaults/templates/_helpers.tpl
charts/kubewarden-defaults/templates/allow-privileged-escalation-policy.yaml
charts/kubewarden-defaults/templates/capabilities-policy.yaml
charts/kubewarden-defaults/templates/host-namespace-policy.yaml
charts/kubewarden-defaults/templates/host-path-policy.yaml
charts/kubewarden-defaults/templates/pod-privileged-policy.yaml
charts/kubewarden-defaults/templates/user-group-policy.yaml
charts/kubewarden-defaults/tests/failure_policy_test.yaml

Currently the default set of policies are applied in monitor mode, but cause all pods to be rejected if the kubewarden service is down. This should not be the case if the user's intention is to monitor instead of protect.
I've added a couple of tests to a new suite for kubewarden-defaults to check this behaves as expected
N/A 
Prevent catastrophic failure when kubewarden service is unavailable if in monitor mode

fix(kubewarden-defaults): set `failurePolicy: Ignore` if mode == "monitor"

---

.github/workflows/e2e-tests.yml
.github/workflows/helm-chart-release.yml
README.md

Take advantage of e2e test rewrite, we can now run multiple configurations.
Requires: https://github.com/kubewarden/kubewarden-end-to-end-tests/pull/119
Tests are triggered on:
```
Dispatch: custom parameters
PR: install + tests from PR
Nightly:
- install from main with latest images (to check if we can tag and release)
- install tagged charts (refrence job to make sure product works, most stable case)
Release (stable, rc, beta):
- install release
- upgrade from previous stable to this release
- install on oldest supported k8s
```
I also removed setup-helm action, helm is installed by default on github runners.

New schedule for e2e tests

---

charts/kubewarden-controller/templates/post-install-hook.yaml

Fix #556
add image pull secrets to a values file:
```
imagePullSecrets:
- name: mySecret
```
```shell
helm install --wait -n kubewarden kubewarden-controller charts/kubewarden-controller --values myvalues.yaml
```
Images of the post-install-hook can be pulled even if the private registry needs authentication.
if imagePullSecrets are not set the part will be ignored and not created.
None Known
None Known

added imagepullsecrets

---

updatecli/scripts/install_crds.sh

We forgot to automatically move the {,cluster}admissionpolicygroups YAMLs to kubewarden-crds when consuming the controller CRDs.tar.gz artifact.
This resurfaced because we are now updating them with the short names.
See https://github.com/kubewarden/helm-charts/pull/561/commits/85adc7364d103f4491a36105df94209a05b43ab0.

ci: Automatically copy {,cluster}admissionpolicygroups YAMLs to kubewarden-crds

---

.github/workflows/helm-chart-release.yml

Closes https://github.com/kubewarden/helm-charts/issues/565.
Use actions/attest-build-provenance to generate and upload the provenance attestation as an OCI artifact layer.
Since we need the digest of each helm chart OCI artifact so we can push the attestation, unroll the `for helm push` that existed before. Decided to duplicate those bash scripts instead of creating a new script and makefile target because they basically set the `GITHUB_ENV` vars and call `helm push` and `cosign `with them.
Successful run: https://github.com/viccuad/helm-charts/actions/runs/11484306246/job/31961771613
https://github.com/viccuad/helm-charts/attestations

ci: Generate and push provenance attestations for charts

---

.github/workflows/e2e-tests.yml

Remove test support for kubernetes 1.23 and 1.24. See https://github.com/kubewarden/kubewarden-controller/issues/913#issuecomment-2437752760

Oldest supported k8s is 1.25

---

.github/workflows/helm-chart-release.yml

Updates the release CI to call Chart releaser directly to allow us more control over the process on how the artifacts are signed and uploaded.
Fix #574

fix(ci): call chart releaser directly.

---

charts/kubewarden-controller/questions.yaml
charts/kubewarden-controller/templates/deployment.yaml
charts/kubewarden-controller/templates/opentelemetry-collector.yaml
charts/kubewarden-controller/templates/post-install-hook.yaml
charts/kubewarden-controller/templates/service.yaml
charts/kubewarden-controller/tests/telemetry_configuration_test.yaml
charts/kubewarden-controller/values.yaml

Adds additional telemetry configuration fields to allow users to add their custom OpenTelemetry collector configuration together with the Kubewarden configuration.
Fix #573 
Needs https://github.com/kubewarden/kubewarden-controller/pull/934

feat: extra OPTEL collector configuration.

---

charts/kubewarden-controller/questions.yaml

Updates the questions.yml to show the sidecar collector metrics and tracing exporter configuration fields only when the metrics/tracing is enabled.
Related to https://github.com/kubewarden/helm-charts/issues/597
[simplescreenrecorder-2024-12-16_10.23.41.webm](https://github.com/user-attachments/assets/205b42a4-d6ef-46c0-8c77-d45d19b9798d)

fix: show sidecar fields when metrics is enabled.

---

charts/kubewarden-controller/templates/post-install-hook.yaml
charts/kubewarden-controller/values.yaml
updatecli/updatecli.d/update-deps.yaml

Fix https://github.com/kubewarden/kubewarden-controller/issues/907
E2E tests.
This PR bumps the kuberlr-kubectl image to v3.0.0. Once this is merged, I will have an eye for the updatecli automated bump to v4.0.0 as a means of testing that automation.

deps: Migrate to rancher/kuberlr-kubectl

---

charts/kubewarden-controller/templates/pre-delete-hook.yaml

Part of https://github.com/kubewarden/kubewarden-controller/issues/907.
This mirrors the securityContext changes of the post-install-hook.yml Job. Add `runAsUser`, `runAsGroup` for rancher/kuberlr-kubectl image.
CI

fix: Set runAsUser, runAsGroup also in pre-delete-hook.yaml

---

charts/kubewarden-controller/values.yaml

See: https://github.com/kubewarden/kubewarden-controller/issues/974
Workaround for https://github.com/kubewarden/kubewarden-controller/issues/974
CI

deps: Revert to kubewarden/kubectl image for hooks

---

.github/workflows/update-charts.yml
.github/workflows/update-dependencies.yaml

Fix https://github.com/kubewarden/helm-charts/issues/324
This depends on a GH app with the correct permissions installed on the repo or org, and on `APP_ID`, `APP_PRIVATE_KEY` present as repo secrets.
By running updatecli with this token, GH will trigger workflows for PRs.
See this PR created by my own analogous GH App, where the bot opened the PR and the CI triggered automatically and correctly:
https://github.com/viccuad/helm-charts/pull/7
This is unclear to me yet and will be cleared after we merge this. By using a GH app and the secrets on the repo, it seems that forks will stop working for those things that need the GH app (right now, the policy and images dependency workflow).

feat: Generate and use token from GH app

---

.github/workflows/e2e-tests.yml

E2E test failed on docker rate limit: https://github.com/kubewarden/helm-charts/actions/runs/13378490082/job/37362615670#step:7:23
This PR applies dockerhub authentication that we created for this purpose.

Authenticate k3d registry to dockerhub

---

.github/workflows/e2e-tests.yml

Upgrade test will install last released version of kubewarden.
Then it would upgrade into charts from main using latest images.
Related issue: https://github.com/kubewarden/kubewarden-end-to-end-tests/issues/142
Local run: https://github.com/kravciak/helm-charts/actions/runs/13672080889/job/38224340721

Schedule upgrade test on nightly job

---

charts/kubewarden-controller/values.yaml

Provide default chart values that allow our stack to run inside of a Namespace where the PSA `restricted` profile is enforced.

feat: support running the Kubewaden stack with PSA `restricted` enforced

---

.github/workflows/e2e-tests.yml

Code works on my fork but skips all tests on official repository.
Reverting to previous condition to test 1.24.0-rc1 release.
Broken release tests: https://github.com/kubewarden/helm-charts/actions/runs/14619731131

Disable check for workflow_run name

---

charts/kubewarden-controller/Chart.yaml
charts/kubewarden-crds/Chart.yaml
charts/kubewarden-defaults/Chart.yaml

Fix https://github.com/kubewarden/helm-charts/issues/666.
Helm chart RC only, the images stay with `:1.24.0-rc1`.
Fixes some `appVersion` not being bumped, as well as their matching `catalog.cattle.io/upstream-version`
For completion, here is a comparison with the last GA releae, v1.23.0:
https://github.com/kubewarden/helm-charts/compare/kubewarden-defaults-3.1.0...viccuad:helm-charts:main
CI

Helm chart release v1.24.0-rc2

---

charts/kubewarden-controller/questions.yaml
charts/kubewarden-controller/templates/deployment.yaml
charts/kubewarden-controller/tests/priorityClassName_test.yaml
charts/kubewarden-controller/values.yaml
charts/kubewarden-defaults/questions.yaml
charts/kubewarden-defaults/templates/policyserver-default.yaml
charts/kubewarden-defaults/tests/priorityClassName_test.yaml
charts/kubewarden-defaults/values.yaml

Fix https://github.com/kubewarden/helm-charts/issues/660
For both charts:
- Add new `.global.priorityClassName` value
- Add new entries questions.yml
- Add Helm unittests
CI.
questions.yaml are untested so far (albeit changes are trivial).

feat: Add `.global.priorityClassName` to kubewarden-controller, kubewarden-defaults charts

---

charts/kubewarden-controller/Chart.yaml

According to [Release Planning](https://confluence.suse.com/display/EN/Tentative+Release+Planning) Rancher 2.12.0 should be out 20 Jun, which is before our next release.
Would it make sense to add it to this release? We have rancher 2.12.0-alpha1 now.

feat: Declare support for Rancher 2.12.X

---

README.md

Fix https://github.com/kubewarden/kubewarden-end-to-end-tests/issues/176
Add Github badge to track test status.

Add GitHub badge for airgap E2E test

---

.github/workflows/e2e-backup-restore.yml

Fix https://github.com/kubewarden/kubewarden-end-to-end-tests/issues/191
This PR adds workflow file to trigger the backup-restore test for kubewarden resources
backup-restore test from my fork https://github.com/juadk/helm-charts/actions/runs/16470799097 ✅ 
1. Install K3S
2. Install rancher backup-operator components (from Victor's fork because the PR is not merged yet => https://github.com/rancher/backup-restore-operator/pull/789)
3. Install Kubewarden controller with: `auditScanner.policyReporter=true` and  `auditScanner.cronJob.schedule=*/2 * * * *"` 
4. Install Kubewarden defaults with  `recommendedPolicies.enabled=true`
5. Create a privileged pod to trigger a policy report, make sure the policy report is generated.
6. Add a backup resource using ` rancher-resource-set-full`, make …

Add backup-restore test

---

.github/workflows/e2e-tests.yml

Currently we trigger release tests for every merged pull request.
This change skips release tests unless PR is named `Helm chart...`, we use `Helm chart (major|minor|patch) release` pattern.
Test run: https://github.com/kravciak/helm-charts/actions/runs/16776664194

Trigger release tests only for specific jobs

---

updatecli/updatecli.d/update-chart-deps.yaml
updatecli/values.yaml

Updates the updatecli script used to update dependencies replacing the autodiscovery by source/target steps. Otherwise, the Hauler manifest will be out of date due the order of execution of the steps.
Run CI to update dependencies.
The [PR](https://github.com/jvanz/helm-charts/pull/170) is generated by CI with this changes

fix(ci): replace autodiscovery by source/target steps.
